### ISSUE TITLE
ncf_manager: Improve Credit Notes Usability

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#1]
#### Impacted versions:
11.0

#### Steps to reproduce:
Crear una nota de crédito

#### Current behavior:
- El comportamiento de las facturas de notas de crédito no es a prueba de errores, y puede crear problemas al generar un reporte fiscal, ya que el campo fiscal "Afecta a" se podría quedar vacío.

#### Expected behavior:
- Campo "origin":
    - Debería estar debajo del Partner (solo cuando sea out_refund)
    - Debe decir "Afecta A" (solo cuando sea out_refund)
    - Readonly cuando ya tenga contenido (!= False)

**Comment by edsersolis** [comment]
1. Las notas de crédito deben poder ser emitidas también cuando hay un pago aplicado a estas.

2. Para pagar con una nota de crédito a una factura de cliente, Odoo debe pedir el número de NC para aplicar el pago (solo los números y que el llene las cantidades faltantes con 0). Validar si esta NC había sido generada y con saldo a favor del cliente aún.

3. ncf_pos requiere también de poder manejar las notas de crédito de igual manera que el punto anterior.

**Comment by gustavovalverde** [comment]
De forma general este requirimiento fue cumplido, sus detalles que no sean los correctos serán validados en #54
