### ISSUE TITLE
NCF mal digitado: El comprobante *B0100000002* no tiene la estructura correcta valide si lo ha digitado correctamente

### ISSUE THREAD

**Issue by herohat** [odoo-dominicana/l10n-dominicana#100]
#### Impacted versions:

Develop branch

#### Steps to reproduce:

- Crear una factura de compra (Purchases)
- Asignarla a un cliente con RNC
- Escoger el tipo de costos y gastos 02
- Poner el NCF B0100000002

#### Current behavior:

Devuelve el error:

NCF mal digitado

El comprobante *B0100000002* no tiene la estructura correcta valide si lo ha digitado correctamente

#### Expected behavior:

Validar factura o error de comprobante no válido en la DGII.

#### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/1145973/38439811-0e1b6f64-39ad-11e8-8027-2c8f30a0d6f5.png)

**Comment by gustavovalverde** [comment]
Bueno, el tema ahora mismo es que sí...todavía la estructura (al presente) no ha cambiado. Y la validación de la estructura se está haciendo con el formato viejo. Tengo que hacer un PR en stdnum.do para agregar la estructura nueva al validador.

**Comment by herohat** [comment]
No entiendo, si esta es una nueva localización que se esta rescribiendo para la nueva normal del DGII, ¿por qué se esta mirando y validando la secuencia de NCF vieja?.

Entiendo que aún el DGII no tenga esto en línea pero ya la validez del NCF  solo se podrá saber hasta entonces pero en cuento a estructura debería estarse validando está nueva.    ¿O a caso a partir del 1ero. de mayo tendremos excepciones y se podrán agregar NCF del viejo formato?

**Comment by edsersolis** [comment]
@herohat Dado que la estructura nueva entrará en vigencia el 1ro de Mayo, la declaración de impuestos se hace hasta el 15 de Mayo y existen NC que pueden ser aplicadas hasta Junio (... y hasta Abril 2019 en algunos casos)... la localización tendrá que manejar ambas secuencias.

Dicho esto está bien la válidación que se tiene hasta el momento, lo que si se debe incluir las nuevas secuencias a la validación.

No obstante se deberá hacer un mantenimiento del código pasado este tiempo para eliminar esa validación y hacer el código más eficiente.

**Comment by gustavovalverde** [comment]
@herohat ya el cambio fue realizado en **stdnum** https://github.com/arthurdejong/python-stdnum/commit/8204ac6327259972962cdc926a24f47ff7285ab5

Sin embargo, habría que instalar el stdnum directo desde git con pip para poder probar de inmediato.

**Comment by gustavovalverde** [comment]
@herohat ya puedes instalar pip install python-stdnum==1.9, que ya incluye este cambio.
