### ISSUE TITLE
[ncf_pos] Permiso para emitir una NC

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#105]
#### Impacted versions:
10.0 - 11.0

#### Steps to reproduce:
Crear una factura desde el POS.
Buscar la factura creada.
Emitir una nota de crédito a partir de esta factura.

#### Current behavior:
Cualquier usuario de POS puede hacerlo.

#### Expected behavior:
Que solo los usuarios con el permiso para emitir la NC puedan hacerlo.

**Comment by eneldoserrata** [comment]
Ademas de esos permisos de deben incluir todos los demas segun imagen>
![Screen Shot 2018-04-10 at 11.33.34 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab4bf61759d7000115d3d3f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ee0c2852415c4abc30254d58eeb9cb74fce36f34985619e8803f5971976b12aee98b16b806ba208a1c82b2efd94491fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e24e52a0173464e2773e6e0a.png)

**Comment by edsersolis** [comment]
Cuando se realicen las funcionalidades descritas en https://github.com/odoo-dominicana/l10n-dominicana/issues/37

También se necesitarán:
1. Permiso para acceder a mesas tomadas.
2. Permiso para reasignación de mesas.
3. Permiso para separar y unificar ordenes.

**Comment by juhenriquez** [comment]
@gustavovalverde creo esto se puede cerrar.
