### ISSUE TITLE
[ncf_pos] Error no descriptivo al vender a cliente sin RNC

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#117]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Abrir sesión en POS
- Hacer nueva orden
- Crear cliente con NCF de cualquier tipo.
- No colocar RNC a cliente.
- Realizar pago de orden.

#### Current behavior:
- Se muestra error no descriptivo.
- Permite colocar tipo de comprobante al cliente sin un RNC.
![image](https://user-images.githubusercontent.com/6585110/38771149-b0cdd690-3feb-11e8-9525-c12a16d9df27.png)

#### Expected behavior:
- No permitir colocar tipo NCF sin un RNC.
- Mostrar error descriptivo.

**Comment by eneldoserrata** [comment]
en cual commit hiciste esa prueba?

**Comment by eneldoserrata** [comment]
@akevinieron @frankpenalo favor revisar este issue ya que lunes o martes debemos terminar el pos de este branch

**Comment by akevinieron** [comment]
@edsersolis acabo de probar de reproducir este error en la ultima version que tenemos en el repo pero no lo logré. Posiblemente este bug haya sido solucionado en los ultimos commits.

El funcionamiento actual es que cuando esta seleccionado un cliente con cualquier tipo de Tipo fiscal (el label NCF en el formulario) pero no tiene RNC, al momento de darle a pagar o validar la factura se manda un error de que debe tener RNC.

Pruebalo por favor y dejame saber.

Probando esto he visto que falta la misma validacion al momento de crear el cliente.

**Comment by edsersolis** [comment]
No está presente el error en la ultima version.
