### ISSUE TITLE
[ncf_pos] El botón 'Todas las órdenes' no trae ninguna información

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#121]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Crear varias facturas
- Presionar el botón "Todas las órdenes"

#### Current behavior:
- No se muestra ninguna de las recién hechas

#### Expected behavior:
- Mostrar las órdenes

**Comment by eneldoserrata** [comment]
Por el tema de los NCF esto no es posible para la version online del POS y se debe de usar el botón buscar.

Cuando se implemente la version offline sera posible agregar a esa lista al momento de de validar.

Por otra parte si refresh la pantalla las carga de la misma forma que lo hacia la del indu

NOTA IMPORTANTE: Por experiencia siempre es mejor que se tenga que buscar ya que eso obliga a tener mas control de que el cliente al momento de hacer una devolucion tenga que llevar su factura y de no tenerla pase a un nivel mas alto

**Comment by gustavovalverde** [comment]
Muchas veces pasa que quieren hacer una reimpresión de una factura que hicieron en la mañana, si los cajeros no tienen acceso al backend de facturas (que no deben tenerlo), se les haría imposible hacer esto.

Por cierto, no me quedó muy claro como interviene el tema de los NCF en esta pantalla, porque las que se acaban de generar están en el localstorage incluso.

**Comment by eneldoserrata** [comment]
Aun no hemos implementado reimpresión eso quedaría ahí
