### ISSUE TITLE
[11.0] ncf_pos: Cruce de ordenes de PTV

### ISSUE THREAD

**Issue by JpGarciiia964** [odoo-dominicana/l10n-dominicana#124]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Iniciar el PTV.
- Realizar ventas.
- Dar clic en el botón para imprimir todas las ordenes del PTV.

#### Current behavior:
Al momento de actualizar a la nueva localización cuando se imprimen todas las ordenes de una sesión de PTV, esta se cruza y trae las ordenes de todos los TPV disponibles en la instancia.

#### Expected behavior:
Al dar clic en el botón para imprimir todas las ordenes, solo se impriman las ordenes del PTV, que haya ejecutado dicha orden.

**Comment by eneldoserrata** [comment]
@JpGarciiia964 puedes enviar un screen shot del boton que mencionas "Dar clic en el botón para imprimir todas las ordenes del PTV."

**Comment by JpGarciiia964** [comment]
![deepinscreenshot_seleccionar area_20180417131254](https://user-images.githubusercontent.com/26505235/38885508-32de6a3a-4241-11e8-8fc8-e80ad9b19380.png)

**Comment by eneldoserrata** [comment]
@JpGarciiia964 me puedes decir que modulo instala ese boton?

**Comment by JpGarciiia964** [comment]
El del posbox

**Comment by gustavovalverde** [comment]
@frankpenalo, me parece que esto es cuando el módulo de todas las órdenes se pone para que no solamente considere lo de la sesión, sino también días pasados. Entonces liga las sesiones.

**Comment by gustavovalverde** [comment]
@frankpenalo @eneldoserrata hay que modificar el botón "Todas las Órdenes", para que aunque muestre los últimos 'N' días, sea solamente del punto de ventas actual y de todos.
