### ISSUE TITLE
Reconcile payemnt with invoice on pos order after invoice validation.

### ISSUE THREAD

**Issue by eneldoserrata** [odoo-dominicana/l10n-dominicana#125]
#### Impacted versions:
 11.0

#### Steps to reproduce:
Create invoice from pos with ncf_pos installed

#### Current behavior:
the invoice is not reconciled in accounting even though it was already paid at the point of sale
until the pos session closes.

#### Expected behavior:
The invoice must be reconciled with the payment line of pos.order after validation so that these payments are not opened and are reconciled by mistake with other documents.

**Comment by edsersolis** [comment]
@eneldoserrata que crees si en vez de conciliar se marque como pagada pero sin conciliar? Esto pensando en el caso de que a la cajera le falte dinero al momento del cierre. Que sucedería?

Otra opción para el problema que planteas pudiera ser una restricción que mientras esté esa sesión abierta no permita un pago por el backend. Quizás un estado nuevo para las facturas que diga algo como "En proceso".

**Comment by gustavovalverde** [comment]
Yo opto porque esto sea un módulo separado que dependa de ncf_pos, así está a opción de cada quien si se concilia en tiempo real o no.
