### ISSUE TITLE
[ncf_pos] Validación de NC no sucede si solo se introducen dos digitos

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#127]
Si en el punto de venta se colocan solamente dos digitos el sistema no arroja la alerta de que no se digito un NCF correcto. 

Adicionalmente el campo está viniendo con datos basura, provocando que el usuario debe borrar antes de digitar. El campo debe venir vacio.

**Comment by eneldoserrata** [comment]
@edsersolis puedes darmos la rama y el commit en el que estas?

**Comment by edsersolis** [comment]
Este es: https://github.com/odoo-dominicana/l10n-dominicana/commit/5bcc17d249769f39c709c150621ed27536cb852b

**Comment by frankpenalo** [comment]
Hasta el commit https://github.com/odoo-dominicana/l10n-dominicana/commit/5bcc17d249769f39c709c150621ed27536cb852b sólo estaba el frontend para agregar una NC como forma de pago y luego fue que se hizo la lógica del backend.

@edsersolis favor actualizar al commit más reciente y verificar nuevamente.

**Comment by edsersolis** [comment]
Estoy probando en Odoo.sh directamente. Siempre tomo el último disponible.

Pero Odoo.sh no ha querido saber mucho de @eneldoserrata en estos días y ese es el último disponible :sweat_smile:

Cierro el issue si dicen que esta funcionando, lo tengo en cuenta para seguir probando.
