### ISSUE TITLE
11.0 [ncf_manager]: No permite validar facturas sin Privilegios de Configuración

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#128]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Crear una Factura
- Validarla

#### Current behavior:
- Da error de acceso en el modelo **ir.sequence**
- En otros casos da error en el modelo **ir.sequence.date_range**
![image](https://user-images.githubusercontent.com/16890942/38930864-5a2af7e0-42df-11e8-9ab7-2f8fb74be89b.png)

#### Expected behavior:
Los usuarios de Ventas y Facturación pueden validar facturas.

**Comment by edsersolis** [comment]
El error del ir.property no será relacionado aquí también? @gustavovalverde

**Comment by yasmanycastillo** [comment]
Entendido, voy a revizar y corrgir.

**Comment by gustavovalverde** [comment]
Se arregló en ventas con el commit de @eneldoserrata, pero sigue pasando en compras dando el de **ir.sequence.date_range**

**Comment by gustavovalverde** [comment]
@yasmanycastillo pudiste darle un ojo?

**Comment by yasmanycastillo** [comment]
Ahh veo que se reabrio, dejame aprovechar y verlo.

**Comment by yasmanycastillo** [comment]
@gustavovalverde acabo de actualizar el repo, y me valido bien. Voy a crear otra instancia para probar. Mi usuario tenia los permisos básicos.

**Comment by gustavovalverde** [comment]
Intenta con un journal de Proveedores Informales

**Comment by yasmanycastillo** [comment]
Igual me deja, alguna configuración que deba tomar en cuenta? Los diarios estan configurados de forma correcta tanto de Ventas como de Compras.
