### ISSUE TITLE
[ncf_pos] Permite hacer varias NC a una misma factura

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#135]
Probando en el commit https://github.com/odoo-dominicana/l10n-dominicana/commit/e891cdbb8f86076adeca284e15085a0eaf2d5876 el POS presenta los siguientes comportamientos:

1. Si se realiza una venta y luego se intenta hacer una NC a esa venta, la factura no aparece en el listado. Hay que dar refresh para que esta aparezca.
2. Si se aplica una NC a una factura y luego se intenta hacer otra NC a la misma factura está aparece como refunded. Sin embargo, si hacemos un refresh del browser está aparece nuevamente disponible para hacerle una NC.
3. Ninguna de las NC que cree, duplicadas y no duplicadas, se muestran en la contabilidad.
4. La columna de estado no indica nada.
5. He intentando crear un contacto mediante RNC desde el POS y no lo he logrado de ninguna manera.

**Comment by eneldoserrata** [comment]
Si se realiza una venta y luego se intenta hacer una NC a esa venta, la factura no aparece en el listado. Hay que dar refresh para que esta aparezca.
- La puede buscar utilizando el search tambien es algo que estamos discutiendo por tiene implicaciones de control de que puedan hacer devoluciones si el cliente no lleva la factura yo concidero que debiera de siempre tener el numero de la factura para que la empresa tenga mas control.

**Comment by eneldoserrata** [comment]
@akevinieron @frankpenalo por favor revisar esto para que podamos terminar el release para mañana.

**Comment by eneldoserrata** [comment]
@edsersolis asegurate que el diario de venta que tiene configurado el pos sea ncf_control.

**Comment by edsersolis** [comment]
Ahh tu ves esa es nueva. Dejame probar.

**Comment by eneldoserrata** [comment]
lo que queremos hacer es que si el diario no es ncf_control el pos funcione de forma nativa

**Comment by edsersolis** [comment]
> La puede buscar utilizando el search tambien es algo que estamos discutiendo por tiene implicaciones de control de que puedan hacer devoluciones si el cliente no lleva la factura yo concidero que debiera de siempre tener el numero de la factura para que la empresa tenga mas control.

Entiendo que si, que lo más sano es que el usuario tenga que ingresar el número de la factura y que con las secuencia nuevas no será tan tedioso ingresar el número completo (sin el prefijo B).

**Comment by edsersolis** [comment]
Ahora si encontré una bien buena. En la impresión me da un número impar, pero en la contabilidad me da solo los pares.

Por ejemplo, si hago tres ventas las impresiones me darán los número 1, 3 y 5. Por otro lado, en la contabilidad me muestra 2, 4 y 6.

![image](https://user-images.githubusercontent.com/6585110/39030179-0c860ef8-442e-11e8-9598-c6f4cac14390.png)

**Comment by gustavovalverde** [comment]
> La puede buscar utilizando el search tambien es algo que estamos discutiendo por tiene implicaciones de control de que puedan hacer devoluciones si el cliente no lleva la factura yo concidero que debiera de siempre tener el numero de la factura para que la empresa tenga mas control.

Para eso el módulo pregunta si solo mostrará los de la **sesión actual** o los de **'N' cantidad de días** hacia atrás. Si no queremos que visualicen las ventas de días anteriores ni las de hoy, entonces ponerle una **opción adicional de que no las muestre**; y cada quien que seleccione la que mejor aplique a su realidad. Con esto, el search por factura es global, y la visualización de las mismas en pantalla depende de esta opción (**todos felices**)

**P.D.:**  Es muy común que el cliente pierda la factura y que aún así tenga derecho a reclamar el cambio, pero ya dependerá de la política de la empresa si dejar hacerlo o no (ayer me pasó el primer caso).

**Comment by gustavovalverde** [comment]
cc: @frankpenalo

**Comment by gustavovalverde** [comment]
@frankpenalo @eneldoserrata, esta es medio urgente y peligrosa https://github.com/odoo-dominicana/l10n-dominicana/issues/135#issuecomment-382967894

**Comment by eneldoserrata** [comment]
@edsersolis acabamos de probar el flujo completo y no pudimos reproducir el error cerrare este issue pero si cuando puedas volver a probar te  nuevamente nos dejas saber.
