### ISSUE TITLE
[develop] ncf_pos: No tiene un ticket para el PosBox

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#136]
#### Impacted versions:
11.0

#### Steps to reproduce:
Configurar un POS con el PosBox
Generar una Factura en el POS

#### Current behavior:
No sale con información fiscal

#### Expected behavior:
Que el ticket del PosBox también tenga un formato Fiscal

**Comment by blfernandez** [comment]
Todavia a la espera
