### ISSUE TITLE
[ncf_pos] Ocultar boton Todas las Facturas si el diario factura no tiene ncf_control

### ISSUE THREAD

**Issue by frankpenalo** [odoo-dominicana/l10n-dominicana#138]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Abrir sesión en POS
- Verificar que se muestre el boton **Todas las Facturas** encima del teclado numerico

#### Current behavior:
- Se muestra el boton sin importar si el diario de factura configurado tiene activada la opcion de ncf_control

#### Expected behavior:
- Que solo muestre el boton si el diario de factura configurado tiene activada la opcion de **ncf_control**

**Comment by gustavovalverde** [comment]
No entendí ¿Por qué?
