### ISSUE TITLE
[develop] ncf_manager: Los campos income_type y expense_type deberían fitrar las cuentas asignadas

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#146]
#### Impacted versions:
develop

#### Steps to reproduce:
- Crear una factura
- Seleccionar `income_type` o `expense_type`
- Agregar un Producto

#### Current behavior:
- El producto no filtra las cuentas según el tipo de Ingreso o Tipo de Gasto

#### Expected behavior:
- Las cuentas contables deben también tener los campos `income_type` y `expense_type`, para cuando en la factura se elija una de estas, el producto solo tenga como _domain_ las cuentas contables relacionadas a este Tipo de Ingreso y/o Tipo de Gasto.

**Comment by jlopezg** [comment]
El campo income_type sólo debe ser visible en los siguientes tipos de cuentas:
- Ingreso
- Otros Ingresos
- Activos Fijos
- Activos Corrienes
- Activos No-Corrienes

El campo expense_type sólo debe ser visible en los siguientes tipos de cuentas:
- Costo de Ingreso
- Depreciación
- Gastos
