### ISSUE TITLE
[ncf_manager] Si el usuario crea una factura de compra erronéa no puede eliminarla

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#148]
Si un usuario crea una factura con un número de comprobante erronéo, luego no podrá eliminarla.

Por ejemplo, si ya existe una factura con el NCF terminado en 02 y vuelve a intentar crearla, Odoo le hará la advertencia de que está duplicada.

Le permitirá cancelarla, pero nunca eliminarla porque ya tienen move_name asignado. Además de que como el campo es requerido no le permitirá dejarlo vacío.

Se debe desligar el move_name de esa factura cuando no pase la validación de la DGII (duplicada, no es válida, etc...).

Cuando se desligue no debe eliminar los datos introducidos en el campo, para que en caso de que haya sido mal digitado porque falto algún cero o cualquier otro motivo el usuario no requiera digitarlo por completo.

**Comment by gustavovalverde** [comment]
Es que ese campo de NCF es el mismo del move_name, no son campos diferentes. Pero sí entiendo tu punto, que pasa mucho con las facturas de compra.

@eneldoserrata  hay otro campo que sea como un "trampolín" antes de enviarlo al de move_name?

**Comment by gustavovalverde** [comment]
Si es fiscal, le puse la opción de que con el cambio de diario se limpie el NCF
