### ISSUE TITLE
FUNCIONALIDADES AL CREAR CLIENTE

### ISSUE THREAD

**Issue by vsantosv** [odoo-dominicana/l10n-dominicana#154]
#### Impacted versions:
11.0

#### Steps to reproduce:
Ir a factura de cliente, crear un nuevo cliente, colocar el Nombre de la empresa, guardar el registro

#### Current behavior:
Cuando se graba el cliente como Empresa no especifica que el tipo de comprobante ( en este caso Credito Fiscal) y el cliente persiste como individual y no como empresa.  

#### Expected behavior:
Al grabar un cliente como empresa, adeberia asignarle por default el tipo de comprobante Credito Fiscal y colocar el cliente como tipo Empresa.

**Comment by gustavovalverde** [comment]
@yasmanycastillo solo para estar 100% con esto.

Si el lenght del VAT es == 11, será **Crédito Fiscal**, de lo contrario **Consumidor Final**.

O ustedes prefieren que las facturas que se hagan a personas con cédulas salgan como **Crédito Fiscal**? @vsantosv @eneldoserrata

**Comment by yasmanycastillo** [comment]
@vsantosv, @gustavovalverde si la longitud del VAT  == 9, es un RNC, y por lo tanto se marca dicho cliente como empresa y se le asigna el tipo Credito Fiscal por defecto, de lo contrario se queda como individual.

**Comment by yasmanycastillo** [comment]
@vsantosv @gustavovalverde no recuerdo si la parte de que sobrepase el monto de 50K esta comtenplado, voy a verificar ese flujo y sino esta creare un issue para ello.

**Comment by gustavovalverde** [comment]
@vsantosv el tema es que hay muchos clientes que utilizan la cédula para tener el nombre correcto del cliente, no necesariamente porque le vayan a emitir un comprobante fiscal.
