### ISSUE TITLE
New NCF error in account purchace recieving invoices 

### ISSUE THREAD

**Issue by jpshort** [odoo-dominicana/l10n-dominicana#160]
#### Impacted versions:
Develop

#### Steps to reproduce:
Recibir una factura y validarla con un comprobante valido.

#### Current behavior:
No permite digitar el comprobante enviado por el suplidor, y si el comprobante existe cuando se hace una factura de ventas dice que esta duplicado 

#### Expected behavior:
Cuando se digite el numero de comprobante en el recibo de factura permita grabar los datos. y si la factura al suplidor tambien se le vende con el mismo numero de comprobante no salga la alerta de que esta duplicado.
Se debe tomar en consideracion que hasta el 20 de Mayo los clientes pueden emitir y recibir facturas del mes de abril con  NCF de la norma anterior.

**Comment by gustavovalverde** [comment]
@jpshort, después de ese commit debe funcionarte
