### ISSUE TITLE
[10.0] ncf_manager: Create new customers o supplier searching by name

### ISSUE THREAD

**Issue by jpshort** [odoo-dominicana/l10n-dominicana#167]
#### Impacted versions:
10.0
#### Steps to reproduce:
Crear un cliente o suplidor buscando por nombre y no por RNC o Cedula

#### Current behavior:
Al intentar crear un cliente o suplidor se digita el RNC o Cedula

#### Expected behavior:
Que las consulta a la DGII se pueda hacer digitando el nombre para que permita el listado de sugerencias.

**Comment by gustavovalverde** [comment]
Ahí nos tiene que ayudar @akevinieron, porque el framework de javascript de la v10 es diferente al de la v11.

**Comment by edsersolis** [comment]
@gustavovalverde pon esto en wishlist no bug. No es prioridad pues es un plus no una necesidad y ya esta en v11.
