### ISSUE TITLE
[11.0] ncf_pos: Crear cliente mediante RNC o Cédula

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#168]
En el ncf_pos no está dando la opción para crear el cliente por RNC o Cédula.

1. Si se coloca el RNC o Cédula en el nombre (como se realizaba anteriormente) simplemente lo crea con el RNC como su nombre. 
2. Si se coloca el RNC en el campo Tax ID y sin colocar nombre, el sistema dará un error pidiendo un nombre. Si se coloca se guarda tal cual como se digite, no hace busqueda a la DGII.

**Comment by gustavovalverde** [comment]
10 o 11?

**Comment by edsersolis** [comment]
11
