### ISSUE TITLE
[11.0] ncf_pos: Permite crear un cliente distinto a consumidor final sin VAT

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#169]
Al crear un cliente en el POS este permite elegir Crédito Fiscal y cualquier otro diferente a Ninguno / Consumidor Final sin la necesidad de colocar un valor en el Tax ID.

El error se da luego de intentar completar la venta, sin embargo ya el usuario no puede editar el cliente porque se creó sin RNC. Esto es propenso a que se creen muchos contactos basura.

Entonces:
1. Si el Tax ID está vacío entonces no debiera bloquearse el campo.
2. Si el Tax ID está vacío no debiera permitir guardar el contacto con ningún tipo de comprobante fiscal (sobre todo por la norma nueva que establece que se requiere cédula a consumos mayor de RD$50,000.00).

**Comment by gustavovalverde** [comment]
@edsersolis verifica en el Odoo.sh el commit de Peñalo

**Comment by edsersolis** [comment]
Este PR está demasiado bien. 

@frankpenalo agregó una funcionalidad interesante en la que si hay una única coincidencia ni siquiera necesitas seleccionarla sino que ya la toma. Por ej.: escribes EDSER y de una vez colocará todos los datos como si hubieses escrito un RNC.

Todas las reglas definidas están funcionando correctamente.
