### ISSUE TITLE
[10.0][11.0] ncf_manager: Problemas al digitar RNC o Cédula

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#170]
Cuando se crea un cliente mediante RNC o Cédula existe el problema de que si el usuario que digita lo hace de forma rápida, presionando _ENTER_ tan pronto termina de digitar, el Wizard traerá solo parte del número digitado y no realizará la búsqueda en DGII. Inclusive en una ocasión la validación marca que la cédula fue mal digitada cuando no lo fue (00:43).

Ahora si el usuario se toma una pausa antes de presionar _ENTER_, ahí si trae la información como se requiere (01:19).

Esto es algo crítico dado que el usuario que tiende a digitar mucho, como contables, estarán realizando esto bien rápido y aunque el tiempo de respuesta no vaya a la par porque debe realizar la consulta contra DGII si debe mantener los datos inalterados.

Aquí el comportamiento: https://youtu.be/_SSAXJAWO00

**Comment by andrp92** [comment]
@edsersolis gracias por reportar este issue. @gustavovalverde, estuve analizando el issue y lo discutí con @jlopezg, llegamos a la conclusión que el el issue esta en el feature que te lista los contribuyentes mientras vas escribiendo RNC o nombre. 

La posible solución podría ser agregar un delay o un wait, que hasta que no se reciba la respuesta de la DGII (ya sea con información o un False), que no salga el Wizard.

**Comment by jlopezg** [comment]
@akevinieron @frankpenalo delen un checkout a esto porfa :)

**Comment by edsersolis** [comment]
Si, ayer comentaba con @gustavovalverde que esa puede ser una solución. Un delay de 1 ~ 2 segundos para traer la información. Mientras menos tiempo o más ajustado mejor.

**Comment by jjdelarosa** [comment]
Yo tengoe el error del cual al intentar digitar la cedula no validad la informacion.

> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 650, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 310, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
>     raise value
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 692, in dispatch
>     result = self._call_function(**self.params)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 342, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 335, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 936, in __call__
>     return self.method(*args, **kw)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 515, in response_wrap
>     response = f(*args, **kw)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 931, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 923, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 5095, in onchange
>     record._onchange_eval(name, field_onchange[name], result)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 4990, in _onchange_eval
>     method_res = method(self)
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\ncf_manager\models\res.py", line 182, in onchange_partner_vat
>     def rewrite_due_date(self):
>   File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\ncf_manager\models\res.py", line 153, in validate_rnc_cedula
>     "name", False) or dgii_vals.get("commercial_name", "")
> AttributeError: module 'stdnum.do.rnc' has no attribute 'check_dgii'

**Comment by jlopezg** [comment]
Hola @jjdelarosa 

Puedes decir qué versión del `stdnum` tienes?

**Comment by herohat** [comment]
En la consula, ejecuta:

pip freeze |grep stdnum

**Comment by jlopezg** [comment]
@jjdelarosa 

En tu servidor, en el environment en que tienes corriendo Odoo 11, usas el siguiente comando para ver la versión:
`pip3 show python-stdnum`

Si la versión es menor a 1.9, actualizas con el siguiente comando:
`pip install python-stdnum --upgrade`

**Comment by jjdelarosa** [comment]
Excelente, tenia la version 1.7 despues de la actualizacion funciona de maravilla.

Disculpe que moleste tanto, pero estoy buscando para poder exportar los 606, 607 y 608, existen algun repositorio. Saludos...

**Comment by jlopezg** [comment]
@jjdelarosa estas en el grupo de facebook Odoo Dominicana?

**Comment by jjdelarosa** [comment]
@jlopezg Realmente no tengo Facebook, pero me gustaria pertenercer a la Comunidad.

**Comment by jlopezg** [comment]
@jjdelarosa te recomiendo abrite una cuenta y unirte a la comunidad. De esa forma te enteras de todo lo que se mueve con Odoo a nivel local.

Por cierto, creo que vi en ese grupo que alguien dijo que iba a hacer o estaba haciendo los reportes de la DGII para Odoo.

**Comment by Klauser** [comment]
Buenas noches, Primeramente decir que estoy empezando a usar odoo recientemente, encontre esta maravillosa comunidad de casualidad y despues coger bastante lucha para instalar los modulos, resulta que tengo el mismo problema con los RNC, tengo instalado el stdnum en la version 1.9 e igual me sigue dando problema que al digitar el RNC me dice que es incorrecto.

Muchas gracias de antemano y en espera de poder resolver dicho problema para poder usar este estupendo software, y no tener que estar modificando las facturas en pdf despues de generarlas, que es bastante engorroso.

**Comment by jlopezg** [comment]
Hola @Klauser 

Bienvenido a tu comunidad!

Para actualizar python-stdnum debes considerar el **_environment_** de python en que tu instancia de Odoo está corriendo; ya que Odoo 11 corre sobre python 3, el cual no es la versión que trae tu sistema operativo por default.

Quizás sí hayas actualizado la librería, pero no en el ambiente correcto.

No sé qué tan inclinado estes a este tipo de temas, pero date una vuelta por este link para que veas más o menos cómo va el tema de **Python Virtual Environment**.

https://github.com/jlopezg/odoo-develop-environment

**Comment by Klauser** [comment]
Exactamente ese era el problema, muchas gracias por la ayuda y por la rapida respuesta.

**Comment by gustavovalverde** [comment]
Cerraré este issue, ya que fue implementada una solución de delay varios commits atrás que mejora este comportamiento.

**Comment by rtaveras07** [comment]
Saludos, soy usuario de Ubuntu, estoy implementando en el, pero al momento de agregar los modulos de NCF obtengo este error: Imposible instalar el módulo "ncf_manager" porqué hay una dependencia externa no resuelta: No module named stdnum.do , ya instale por consola y actualice y nada. 
gracias.

**Comment by gustavovalverde** [comment]
Hola @rtaveras07. El mejor lugar para que te asistan con esto es nuestro grupo en Facebook: https://www.facebook.com/groups/odoo.dominicana/

**Comment by jjdelarosa** [comment]
Hermano debes instalar Python-stdom >1.9, odoo por default trae 1.7
