### ISSUE TITLE
[11.0] ncf_manager: Factura de consumo a cliente con RNC

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#185]
La nueva versión del ncf_manager da el siguiente error cuando se trata de validar una factura de consumo cuando el cliente tiene un RNC. Esto puede suceder, no está estipulado en la ley y por ende no debe ser una restricción.

> No debe emitir una Factura de Consumo, a un cliente con RNC.

**Comment by akevinieron** [comment]
@edsersolis lo revise en el ultimo commit de la v11, cree un cliente nuevo con un rnc y luego hice una factura con NCF para consumidor final. Me permitio validar!!

Cuales serian los pasos para reproducir el error que te está dando??

**Comment by gustavovalverde** [comment]
¿Cuál sería el escenario en que se le deba emitir una factura de Consumo a un cliente con RNC?

**Comment by edsersolis** [comment]
Entonces quedamos que se apruebe este PR y luego se haga configurable?

**Comment by NB5055** [comment]
Eso no debería poder ser posible ya que como dice gustavo no es legal
