### ISSUE TITLE
[11.0] ncf_pos: Luego de guardarse un cliente no deja modificarlo

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#190]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Crear un cliente de Consumo con el nombre y el tipo de NCF.
- Grabarlo
- Editarlo para agregarle información adicional

#### Current behavior:
![image](https://user-images.githubusercontent.com/16890942/39663956-d33cf526-5049-11e8-9862-cbb3fce66aa8.png)

#### Expected behavior:
- Deje modificar al contacto luego de haberlo grabado, para agregar información.

**Comment by edsersolis** [comment]
Esto debe discutirse. Quizás ayude a que los usuarios no vendan a un RNC con el nombre de otro cliente como ya ha pasado.
