### ISSUE TITLE
[REF][11.0] ncf_pos: Reestructurar los JS para mejor mantenimiento

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#193]
#### Impacted versions:
11.0

#### Steps to reproduce:
Actualmente toda la lógica de: Gestión de NCF, Todas las Facturas, Notas de Crédito; se encuentra  principalmente en dos archivos: **models.js** y  **screens.js**

#### Current behavior:
Si se le desea dar mantenimiento a una sola de estas lógicas: La de los NCF, por ejemplo, es muy difícil identificar las funciones específicas que gestionan los mismos. Igual para las demás.

#### Expected behavior:
Tener un .js para cada lógica, para que sea más fácil navegar y entender cuál es la lógica real de los NCF.

**Comment by akevinieron** [comment]
Yo propongo #Delete a esto!!
