### ISSUE TITLE
Search partner by name in DGII

### ISSUE THREAD

**Issue by yasmanycastillo** [odoo-dominicana/l10n-dominicana#20]
Estuve probando un poco y puede que sea posible que agreguemos este feature, sin embargo seria bueno poder antes definir los parametros de filtrado, para poder estructurar un algoritmo que seleccione el nombre indicado o mostrar un wizard con N sugerencias y dejar que el usuario escoja de por si.

Espero sus comentarios

**Comment by gustavovalverde** [comment]
Con relación a los parámetros, me parece que en esta primera implementación sería (por ejemplo) tomar el primer string de letras (antes de poner un espacio), y en base a eso dar una recomendación de búsquedas de la DGII, si encuentra alguna.

Mi idea sería que cuando digites un nombre (en quickcreate, y le des a enter o en el form y le des a guardar) te salga un wizard con un treeview que muestre todos los nombres encontrados en DGII, y si seleccionas uno que esa sea la información que se ponga en el form, de lo contrario cancelas y guardas como lo tenías.

**Comment by gustavovalverde** [comment]
@edsersolis alguna idea?
@jlopezg de esto era que estábamos hablando ayer ¿qué otra forma crees prudente de limpiar el string que se le va  a dar a la DGII para la búsqueda?

**Comment by jlopezg** [comment]
A qué te refieres con limpiar?

Estoy un poco fuera de contexto.

**Comment by gustavovalverde** [comment]
@jlopezg la idea es que si escribes Juan José, te busqué todos los Juan José que existen en DGII. Para las compañías es fácil, porque normalmente no son nombres compuestos, pero cuando busquen nombres entonces los resultados serán más amplios.

Por ejemplo, **José López** , debe arrojar pocos resultados porque de repente es José Luis López. Pero si le enviamos solamente José, de repente envía demasiados resultados innecesarios.

**Comment by eneldoserrata** [comment]
El nuevo equipo de Odoo js lo puede hacer ese sera nuestro reto de hoy 👍

**Comment by edsersolis** [comment]
@eneldoserrata no juega :muscle:

**Comment by edsersolis** [comment]
No probé antes del último commit, pero esta presentando el issue que postie en https://github.com/odoo-dominicana/l10n-dominicana/pull/23 y tambien está permitiendo duplicados en ambas busquedas (nombre o RNC)

**Comment by gustavovalverde** [comment]
@eneldoserrata y @yasmanycastillo, con el comentario de @edsersolis en https://github.com/odoo-dominicana/l10n-dominicana/pull/23#issuecomment-367854914 

Esto es por la siguiente validación que hice:
`if self.name.isdigit() and len(self.name) in (9, 11):`

Sin embargo tal vez lo correcto sea:
`if self.name and self.name.isdigit() and len(self.name) in (9, 11):`

Pero no estoy 100% seguro de si self.name cuando sea False terminará esa parte de la condición o si va a seguir, para evitarme esto:
```python
if self.name:
    self.name.isdigit() and len(self.name) in (9, 11):
```

**Comment by gustavovalverde** [comment]
Cerraré esto como issue, ya que realmente fue implementado, y los issues subsiguientes deben estar por separado.
