### ISSUE TITLE
[10.0-alpha] País por deafult en creación de partner

### ISSUE THREAD

**Issue by WildyEstephan** [odoo-dominicana/l10n-dominicana#206]
#### Steps to reproduce:
Probando branch 10.0-alpha. 
Al crear un partner con el RNC el país que se pone por default es Dominica en vez de República Dominicana.

#### Video/Screenshot link (optional):
![capture-20180511-100459](https://user-images.githubusercontent.com/16001459/39928437-5762866e-5503-11e8-963e-d1c14ab76a65.png)

**Comment by gustavovalverde** [comment]
Aquí aplican uno de esos comentarios que te enseñé @eneldoserrata.

Déjame verificar el blame de eso (espero no haya sido yo) 😅
