### ISSUE TITLE
ncf_manager: editar tipo de comprobante despues de haber validado una factura 

### ISSUE THREAD

**Issue by Amartinez02** [odoo-dominicana/l10n-dominicana#220]
#### Impacted versions:
11 

#### Steps to reproduce:
1-Registro de facturas
2-Validar factura
3-Cancelar factura
4-Poner en borrador

Al proner en borrador para editarla, no debería permitir editar el tipo de comprobante.

**Comment by eneldoserrata** [comment]
PR ready #221
