### ISSUE TITLE
Error validating RCN/Cedula after getting data from DGII

### ISSUE THREAD

**Issue by jpshort** [odoo-dominicana/l10n-dominicana#224]
#### Impacted versions:
Version 10

#### Steps to reproduce:
Crear suplidor o clientes con el RNC/CEDULA
#### Current behavior:
Al momento de digitar el RNC/Cedula no permite crealos debido a un error

#### Expected behavior:
Crear el cliento y/o suplidor

#### Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/12738468/40889809-cc7da7b4-673a-11e8-80a4-eb4672ee3a93.png)

**Comment by herohat** [comment]
Este issue ya fue reportado en el pasado y corregido.   Mira este hilo: https://github.com/odoo-dominicana/l10n-dominicana/issues/94  verifica en que rama estás y si esta actualizada así como las librerías.

**Comment by edsersolis** [comment]
Como indica @herohat esto no es un issue de la localizacion. Es un modulo de validacion que tienen instalado allí y que no funciona para RD.
