### ISSUE TITLE
Permiso de creación de factura de venta (10.0-alpha)

### ISSUE THREAD

**Issue by herohat** [odoo-dominicana/l10n-dominicana#225]
#### Impacted versions:

10.0-alpha

#### Steps to reproduce:

Crear una factura de venta usando el diario de crédito fiscal 

#### Current behavior:

Al intentar guardar la factura, sale este error:

Lo sentimos, usted no está autorizado para modificar este documento. Sólo usuarios con los siguientes permisos están autorizados a hacer esto:
- Administration/Settings

(Modelo de documento: ir.sequence)

#### Expected behavior:

Que los usuarios sin acceso a Administration/Settings puedan crear y guardar facturas de ventas.

#### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/1145973/40890960-1069904e-674c-11e8-9eb1-380079ab58ce.png)

**Comment by gustavovalverde** [comment]
Sí, tengo pendiente arreglar estos permisos.

**Comment by edsersolis** [comment]
https://github.com/odoo-dominicana/l10n-dominicana/issues/219
