### ISSUE TITLE
Error: Notas de credito deben ser tipo 04

### ISSUE THREAD

**Issue by ctactuk** [odoo-dominicana/l10n-dominicana#229]
Saludos,

He tratado de agregar una ratificativa ( nota de credito ) agregando el NCF de la nota de credito que contiene B04... como se muestra en la imagen a continuación y me está dando el error "Las Notas de credito deben ser tipo 04, este NCF no es de este tipo". Agradecería su ayuda en esto.

#### Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/4774542/41044604-a0946b24-6974-11e8-82a3-187309018acf.png)

**Comment by gustavovalverde** [comment]
Gracias por el reporte @ctactuk, ya fue corregido.

**Comment by ctactuk** [comment]
@gustavovalverde gracias, voy a verificarlo.
