### ISSUE TITLE
[ncf_invoice_template] Siempre tomar Parent para la Razon Social

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#231]
Cambiar lineas 201 a 206 del report_invoice.xml para:

```
                    <t t-if="len(o.partner_id.vat) == 9 and (o.partner_id.parent_id.name != False)">
                        <strong>RNC CLIENTE:</strong>
                        <span t-field="o.partner_id.vat"/><br/>
                        <strong>RAZÓN SOCIAL:</strong>
                        <span t-field="o.partner_id.parent_id.name"/><br/>
                    </t>
```

**Comment by gustavovalverde** [comment]
El problema que veo con esto, es que si el usuario no tiene parent, entonces va a explotar; al menos que se dupliquen los if en cada condición para que valide si hay parent, y si no que ponga el del partner. 

Lo correcto (sin desarrollo) sería el uso de 3 direcciones, y que a la de facturación se le ponga el parent.

**Comment by gustavovalverde** [comment]
Coregido con 502feb3
