### ISSUE TITLE
[10.0][11.0][ncf_manager][IMP] Diario de Compras relacionado al Proveedor

### ISSUE THREAD

**Issue by jlopezg** [odoo-dominicana/l10n-dominicana#233]
En las **Facturas de Proveedor**, me parece que el **Diario** debe venir relacionado al **Proveedor** en si; creándole un campo **Diario de Proveedor** en el contacto, de manera que la factura lo ponga de forma predeterminada.

Considerando que para un Proveedor, el Diario de Compras siempre (entiendo yo) será el mismo, se ahorraría un paso e incluso errores en colocar este campo.

**Comment by gustavovalverde** [comment]
Aprobado. @andrp92 Dale ahí.

**Comment by yasmanycastillo** [comment]
Encontre este modulo que hace justo eso.

[https://www.odoo.com/apps/modules/11.0/partner_journal_default/]

**Comment by andrp92** [comment]
@gustavovalverde creo que este issue fue resuelto con este commit 745e601, se puede cerrar ya?
