### ISSUE TITLE
[11.0][ncf_manager] Factura de compras no completa Cuenta automáticamente

### ISSUE THREAD

**Issue by jlopezg** [odoo-dominicana/l10n-dominicana#239]
#### Impacted versions:
11.0

#### Steps to reproduce:
Crear Factura de Proveedor
Completar información: Proveedor, NCF, Fecha de factura, Tipo de Costos

#### Current behavior:
El campo Cuenta no se completa automáticamente.

#### Expected behavior:
Traer una cuenta desde el Proveedor o desde el Diario

#### Video/Screenshot link (optional):
<img width="663" alt="screen shot 2018-06-28 at 12 26 02 p m" src="https://user-images.githubusercontent.com/16394301/42047517-796c91e6-7ace-11e8-881f-e8fd00d68ff7.png">

**Comment by gustavovalverde** [comment]
Fixed by 6f1e58fd40cc4486d2e82276f7357edb5038d8e3
