### ISSUE TITLE
[11.0] ncf_pos: El botón 'Todas las Facturas' no trae la información filtrada ni la guarda

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#240]
#### Impacted versions:
11.0

#### Steps to reproduce:
- Abrir el POS
- Utilizar el botón *Todas las Facturas*

#### Current behavior:
Empieza a cargar el histórico completo de las facturas sin respetar los parámetros del pos.config. Esto causa que en algunos casos dure hasta 1 minuto cargando, si el cliente tiene mucho histórico.

Luego de salir de la  lista y volver a entrar; carga nuevamente.

#### Expected behavior:
La carga de facturas debería respetar el campo `order_loading_options` del pos.config

**Comment by gustavovalverde** [comment]
@akevinieron @frankpenalo @eneldoserrata; si alguno me puede dar una mano con este. Que ya hay personas que no pueden ni hacer notas de crédito porque se cuelga cargando las facturas.

**Comment by akevinieron** [comment]
@gustavovalverde Esto se puede cerrar ya, no??

**Comment by gustavovalverde** [comment]
Sí; de identificarse algo adicional se abre uno nuevo.
