### ISSUE TITLE
[10.0] Error al crear cliente, con RNC y Contactos

### ISSUE THREAD

**Issue by JpGarciiia964** [odoo-dominicana/l10n-dominicana#245]
#### Impacted versions: 
10

#### Steps to reproduce:
Crear un cliente por RNC y crearle contactos debajo, gaurdar cliente

#### Current behavior:
No guarda el registro creado, da el siguiente error:
Error mientas se validaban las restricciones

#### Expected behavior:
Guardar el cliente con los contactos.

#### Video/Screenshot link (optional):
![deepinscreenshot_seleccionar area_20180704090801](https://user-images.githubusercontent.com/26505235/42279530-0bc09352-7f6c-11e8-9f73-3457fd241006.png)

**Comment by gustavovalverde** [comment]
@yasmanycastillo

**Comment by mamcode** [comment]
@JpGarciiia964 No puedo reproducir el error, puedes dar mas detalle de como estas intentando crear el cliente ?

**Comment by yasmanycastillo** [comment]
@JpGarciiia964 igual que @mamcode no he podido reproducir el error, he creado un cliente con RNC, le he agregado varios contactos relacionados y sin error.

**Comment by mamcode** [comment]
@JpGarciiia964 Pasa todo el traceback del error que se te genera, es probable que sea otro modulo que tengas instalado el que te esta generando esto...

**Comment by JpGarciiia964** [comment]
Saludos, @yasmanycastillo, @mamcode, e corrido el flujo varias veces de la siguiente manera:

Al momento de crear un contacto sin RNC y crearle dos o mas contactos hijos y guardarlo, luego al mismo contacto darle a Editar y agregarle el RNC y darle a Guardar. 
De igual manera se me reproduce el error si creo el cliente directo por el RNC y le agrego mas de un contacto hijo.

**Comment by gustavovalverde** [comment]
@mamcode, cuando tengas una oportunidad por favor le das un ojo a esto.

**Comment by jlopezg** [comment]
@JpGarciiia964 por favor, si puedes graba un video reproduciendo este error.

**Comment by JpGarciiia964** [comment]
![Uploading deepin-screen-recorder_Select area_20180724112803.gif…]()

**Comment by JpGarciiia964** [comment]
![deepin-screen-recorder_select area_20180724112803](https://user-images.githubusercontent.com/26505235/43149266-0a6c3cee-8f35-11e8-8d71-c64cf783da1c.gif)

**Comment by mamcode** [comment]
@JpGarciiia964 @jlopezg Ya pude reproducir el error, yo me encargo.

**Comment by gustavovalverde** [comment]
@jlopezg dale un ojo a este.

**Comment by gustavovalverde** [comment]
@mamcode si puedes porfa
