### ISSUE TITLE
Nombre del cliente en factura de consumidor final

### ISSUE THREAD

**Issue by octagonosrl** [odoo-dominicana/l10n-dominicana#250]
#### Impacted versions:
11.0

#### Steps to reproduce:
Imprimir una factura de consumidor final 

#### Current behavior:
Al momento de imprimir la factura de consumidor final no está el nombre del cliente

#### Expected behavior:
![screenshot_1](https://user-images.githubusercontent.com/32674200/42694977-049ba2de-8682-11e8-9dcd-8891e523fe7d.png)

**Comment by gustavovalverde** [comment]
Corregido con 502feb3b924f997d9b6af643689f4b398a83f551
