### ISSUE TITLE
No se puede crear una NC luego de haberle aplicado NC a la factura

### ISSUE THREAD

**Issue by yasmanycastillo** [odoo-dominicana/l10n-dominicana#276]
#### Impacted versions:
11.0

#### Steps to reproduce:
Crear una factura y validarla.
Generarle una NC.
Aplicar la NC creada a la factura.
Intentar crear una nueva NC.

#### Current behavior:
El wizard no permitira crear una nueva.
#### Expected behavior:
El wizard debe permitir poder crear una nueva.
#### Video/Screenshot link (optional):
![deepinscreenshot_20180909173004](https://user-images.githubusercontent.com/7638760/45269101-0d696c00-b456-11e8-916c-c731ccb924df.png)

**Comment by gustavovalverde** [comment]
Closed by 8139f21a59d37e9a45fcb8e509729b67c382095c
