### ISSUE TITLE
Error al aplicar nota de credito

### ISSUE THREAD

**Issue by alex071995** [odoo-dominicana/l10n-dominicana#278]
#### Impacted versions:

v11
#### Steps to reproduce:

Aplicar NC o ND
#### Current behavior:

No crea la Nota de Credito.
Uncaught Error: Domain filter_refund,=!,discount uses an unsupported operator

#### Expected behavior:

Aplicar nota de credito
#### Video/Screenshot link (optional):

![screenshot from 2018-09-12 13 49 41](https://user-images.githubusercontent.com/7267578/45444008-54dd3b80-b694-11e8-8510-eb2385fda975.png)

**Comment by gustavovalverde** [comment]
Fixed by dbfa68d6c78492b504a81a61889e4e39beaae480
