### ISSUE TITLE
[V10- ncf_pos]Crear Cliente usando el Teclado en Pantalla

### ISSUE THREAD

**Issue by crbll0** [odoo-dominicana/l10n-dominicana#283]
#### Impacted versions:

10

#### Steps to reproduce:

1. Activar el teclado en pantalla del POS
2. Iniciar una sesión de POS 
3. Crear un nuevo cliente y en el nombre introducir el RNC utilizando el teclado en pantalla.

#### Current behavior:
Al introducir un RNC valido, el sistema no consulta en la DGII para trae el Nombre y Tipo de Comprobante.

#### Expected behavior:
Se espera que al introducir los datos con el teclado en pantalla del POS, consulte el RNC en la DGII trayendo los datos necesarios. 

Nota : _Con el taclado fisico si hace el comportamiento esperado._

**Comment by jlopezg** [comment]
Cerrado por falta de mantenimiento v10.
