### ISSUE TITLE
DGII webservices

### ISSUE THREAD

**Issue by yasmanycastillo** [odoo-dominicana/l10n-dominicana#286]
#### Impacted versions:
All

#### Steps to reproduce:
Tratar de crear un nuevo cliente por RNC, lanzara error.
Tratar de crear una factura de proveedor, agregar  NCF del proveedor, lanzara error.

#### Expected behavior:
Crear cliente sin inconvenientes asi como la validacion del NCF de proveedores.

**Comment by gustavovalverde** [comment]
Esto fue causado por un problema con la DGII
