### ISSUE TITLE
Error Al intentar Generar NCF

### ISSUE THREAD

**Issue by Franklinmarte** [odoo-dominicana/l10n-dominicana#308]
#### Impacted versions
10.0
#### Steps to reproduce

Contabilidad->Configuracion->Diarios->Crear

Tipo: Venta

Activar Opcion: Control de NCF

En Secuencias de NCF asignar: B

#### Current behavior
Muestra el siguiente error 
https://pastebin.com/EHAWc3Q7

#### Video/Screenshot link (optional)
Video:
https://mega.nz/#!BVQSHaJB!Hda5O1R6MVcaifww9nXqG0uoBW2jVhMwKUDxoSiQbf8

**Comment by gustavovalverde** [comment]
Debes crearle la primera secuencia de forma manual para que funcione. Realmente esta adaptación se hizo para la v11, pero en la v10 el código es muy diferente.
