### ISSUE TITLE
12.0 [ncf_invoice_template] Falla de instalacion

### ISSUE THREAD

**Issue by danielbaezpena** [odoo-dominicana/l10n-dominicana#309]
#### Impacted versions
12.0 

#### Steps to reproduce
Instalacion Nueva de Odoo 12, al instalar los modulos de l10n-dominicana. Al querer finalizar con el modulo ncf_invoice_template este da un error.

#### Current behavior
No se instala el modulo ncf_invoice_template y da el siguiente error. Todos los demas modulos se instalan correctamente.
https://pastebin.com/mmcWzbmh 

#### Expected behavior
Que se terminara de instalar

**Comment by akevinieron** [comment]
Podrias verificar si tienes la ultima version/commit del repositorio??

**Comment by gustavovalverde** [comment]
Cerrado con este commit: 83e7762523d90ca2e456e4363877653853a44606
