### ISSUE TITLE
Prefill cash config option on POS dont work

### ISSUE THREAD

**Issue by akevinieron** [odoo-dominicana/l10n-dominicana#318]
#### Impacted versions
11.0
#### Steps to reproduce
1- POS Settings -> Check 'Prefill cash payment' option.
2- Make a order on pos and click on Pay button 
#### Current behavior
Don't appear any cash line with the order total amount
#### Expected behavior
A cash line with the order total amount

**Comment by KolushovAlexandr** [comment]
@akevinieron it is not a built-in behaviour. The option prefills amount for cash paymentlines only after you clicked on it.

**Comment by gustavovalverde** [comment]
@akevinieron 💩
