### ISSUE TITLE
[11.0] error al entrar a contactos o clientes

### ISSUE THREAD

**Issue by dixgrake** [odoo-dominicana/l10n-dominicana#325]
#### Impacted versions
11.0
#### Steps to reproduce
crear un usuario con los permisos por defectos de odoo con los siguientes:

ventas: usuario
empleados: empleado

solo hice prueba con estos dos permisos pero si le agrego permisos de facturación no ocurre este problema.
#### Current behavior
al momento de entrar a contactos o clientes inmediatamente sale el error
#### Expected behavior
se espera que cualquier usuario pueda acceder a contactos o clientes independientemente de los permisos de facturación.
#### Video/Screenshot link (optional)

![imagen](https://user-images.githubusercontent.com/34522768/50813701-9d78ce80-12ed-11e9-9eae-6d34666a9521.png)

https://pastebin.com/jvYVHfbG

**Comment by jjdelarosa** [comment]
Que es lo que intentas hacer?

A Cada usuario debes asignarles los permisos que y no puede ver...

**Comment by jjdelarosa** [comment]
@dixgrake ya están trabajando en el Caso, hay un Ticket abierto.

**Comment by gustavovalverde** [comment]
Closed by 8ccc3c77d1406ad29175f1cbdffd4fd3c3cd0a56
