### ISSUE TITLE
fshdkjfshkdf

### ISSUE THREAD

**Issue by akevinieron** [odoo-dominicana/l10n-dominicana#332]
#### Impacted versions
11
#### Steps to reproduce
1. abre el modulo de ventas
2. crea una cotizacion
3. coloca un cliente
4. coloca un producto
5. darle a validar
#### Current behavior
Esta saliendo el siguiente error: fkdsfksdjfkhskdf
sdfskdjfsjkdfh
sfkdhf
#### Expected behavior
Te valide la factura:
y que te apareczfjksdhfsd
#### Video/Screenshot link (optional)
dsjfhsdjkfhskdf

**Comment by gustavovalverde** [comment]
fshdkjfshkdf

**Comment by eneldoserrata** [comment]
🥇
