### ISSUE TITLE
Change 11.0.2.0.0 to V12 in all __Manifest__ files

### ISSUE THREAD

**Issue by jpshort** [odoo-dominicana/l10n-dominicana#334]
#### Impacted versions 
12.0
#### Steps to reproduce
None
#### Current behavior
All the manifest files have still 11.0.2.0.0 as the version
#### Expected behavior
Change the manifest file to V12 version, to avoid configurations mistakes.

**Comment by gustavovalverde** [comment]
Cerrado con 28fe231
