### ISSUE TITLE
[11.0][ncf_manager] Registrar Contacto

### ISSUE THREAD

**Issue by dixgrake** [odoo-dominicana/l10n-dominicana#352]
#### Impacted versions
11.0
#### Steps to reproduce
1. Crear un contacto nuevo con este numero de cédula 03600082980, esta persona esta registrado en la dgii, pueden consultarlo.
#### Current behavior
Error al crear este contacto con este numero de cédula o secuencia 03600082980.
#### Expected behavior
Poder crear este contacto.
#### Video/Screenshot link (optional)
<a href="https://gyazo.com/76c3f78e3f80a0e31c40f7e30acd6220"><img src="https://i.gyazo.com/76c3f78e3f80a0e31c40f7e30acd6220.gif" alt="Image from Gyazo" width="800"/></a>

**Comment by gustavovalverde** [comment]
@dixgrake Y cuál es el error?

**Comment by dixgrake** [comment]
@gustavovalverde https://pastebin.com/print/w3xuyng2

![imagen](https://user-images.githubusercontent.com/34522768/55290231-a33af900-539e-11e9-878b-01680bf319fa.png)

**Comment by gustavovalverde** [comment]
Esto es por un tema de la data de DGII. Fíjate en el nombre comercial que tiene doble comillas en el caso de la cédula que me pasas:

`{"RGE_RUC":"03600082980","RGE_NOMBRE":"JOSE NICOLAS TEJADA JAQUEZ","NOMBRE_COMERCIAL":""MADERA SAN JOSE"","CATEGORIA":"0","REGIMEN_PAGOS":"2","ESTATUS":"2"}
`

**Comment by akevinieron** [comment]
@gustavovalverde La data se sale de la estructura standard y ya veremos como ajustamos eso. Lo que si DEBE haber es un manejo de error amigable para el usuario final.

**Comment by gustavovalverde** [comment]
@akevinieron creo que para este fin hay que entrar todas esas validaciones en un try. Pero como estas cosas explotan en la librería y no en Odoo, me parece que igual el Odoo no captura ese exception; pero tengo que probar.

**Comment by gustavovalverde** [comment]
Fixed in upstream by https://github.com/indexa-git/external_service_addons/commit/b0da344d6b24ea61df695b41ec59816618e530cc
