### ISSUE TITLE
[11.0][ncf_manager] odoo.http: <function odoo.addons.ncf_manager.controllers.controllers.index> returns an invalid response type for an http request

### ISSUE THREAD

**Issue by herohat** [odoo-dominicana/l10n-dominicana#356]
#### Impacted versions
11.0
#### Steps to reproduce
Installa a new version of ODOO 11.0, Install ncf_manager in branch 11.0 and try to create a new contact with RNC.
#### Current behavior
While trying to create a new contact by its RNC, nothing happens after enter the RNC number and hit enter.   In the console I can see this error:

`2019-04-06 14:53:12,708 1 WARNING odoo11 odoo.http: <function odoo.addons.ncf_manager.controllers.controllers.index> returns an invalid response type for an http request
2019-04-06 14:53:12,709 1 INFO odoo11 werkzeug: 172.17.0.1 - - [06/Apr/2019 14:53:12] "GET /dgii_ws/?term=130614938 HTTP/1.1" 204 -`
#### Expected behavior
Find the company name using DGII WS.

**Comment by gustavovalverde** [comment]
¿En cuál commit estás?

**Comment by herohat** [comment]
En este:

commit 20d2afefa8994f117581f39b5867029c4d98e3d2 (HEAD -> 11.0, origin/11.0)
Author: Aleksandr <kolushov@it-projects.info>
Date:   Wed Mar 27 07:06:31 2019 -0400

**Comment by gustavovalverde** [comment]
Probaste en e Odoo.sh? https://www.odoo.sh/project/l10n-dominicana/builds

**Comment by herohat** [comment]
No, uso mi entorno local en Docker.   Antes tenía la versión 11 y funcionaba bien hasta donde recuerdo pero borre todo y volví a instalar desde 0 y allí el problema.  En la versión 10 anda bien, ayer instale la versión 12 y también funciona bien.

Solo en la versión 11 detecte el problema y me parecio extraño pues probe en dos o tres base de datos y por supuesto ejecute en Docker:  pip3 install -r requirements, lo cual me actualizo el python-stdnum a la versión 1.11 y me instalo otra librerías faltantes.  Pensé que podría ser algo de Postgre pues tengo la 9.4 pero ODOO 11 parece correr muy bien en esa versión.   

Tengo pendiente probar en una maquina con Ubuntu que tengo fuera de Docker a ver si el problema se repite

**Comment by gustavovalverde** [comment]
Si te sigue pasando me dejas saber, mientras lo cierro.
