### ISSUE TITLE
Reestructurar diseño localización

### ISSUE THREAD

**Issue by yasmanycastillo** [odoo-dominicana/l10n-dominicana#365]
#### Impacted versions
11.0 12.0
#### Steps to reproduce
Ir a al Diario de Facturas de Clientes,  tratar de crear un punto de emisión.
#### Current behavior
Actualmente no es posible el manejo de Puntos de Emisión (sucursales) por la estructura actual.
#### Expected behavior
Poder menejar los comprobantes desde un modelo aparte, fuera de los Diarios.

**Comment by gustavovalverde** [comment]
Ya casi en producción
