### ISSUE TITLE
Exceso de trabajo

### ISSUE THREAD

**Issue by eneldoserrata** [odoo-dominicana/l10n-dominicana#374]
#### Impacted versions
Todas las versiónes
#### Steps to reproduce
Conocer todas las oportunidades de negocios que Odoo ofrece
#### Current behavior
Mientras todos disfrutan del fin de semana largo paseando en familia los que trabajan con Odoo están programando
#### Expected behavior
Trabajar de 9 am a 12 pm almorzar tranquilamente y abandonar el trabajo a las 6 pm y tener los sábados y lo domingo libres
#### Video/Screenshot link (optional)
No apta para menores de edad

**Comment by yasmanycastillo** [comment]
Eso es parte del  mundo Odoo jejeeje.

**Comment by gustavovalverde** [comment]
😭
