### ISSUE TITLE
Aplicar retenciones al momento de realizar el pago a factura

### ISSUE THREAD

**Issue by yasmanycastillo** [odoo-dominicana/l10n-dominicana#384]
#### Impacted versions
10, 11, 12
#### Steps to reproduce
Generar una factura de proveedor informal u otro proveedor al cual pueda aplicar retenciones, sin incluir los ITBIS de ISR u otra retencion, validar factura.
Al momento de aplicar un pago a dicha factura no es posible indicar que esta factura conlleva retenciones ni aplicarlas.
#### Current behavior
No se pueden aplicar retenciones al momento de pagar.
#### Expected behavior
Poder aplicar retenciones a facturas al momento de realizar el pago.

**Comment by herohat** [comment]
Justo en estos días he estado pensando en eso, pero al generar facturas de ventas al estado los cuales te retienen un 5% de ISR y la única forma que tiene ODOO (o la que yo conozco)  para esto actualmente es que al momento de crear la factura debo seleccionar el impuesto "Retención 5% ISR Gubernamentales" y eso me genera una factura con un balance total ya descontando el 5% de ISR y si bien en el detalle de la factura sale que se desconto ese 5%, la institución correspondiente podría confundirse y hacer nuevamente el descuento. 

En el caso de facturas que nos dan los proveedores pasa algo similar como indicas, pero en ese caso digamos que se tiene más rejuego para hacerlo.

**Comment by yasmanycastillo** [comment]
@herohat actualmente no se considera aplicar esto a ventas solo a compras.

**Comment by herohat** [comment]
@yasmanycastillo entonces el flujo que mencionó de ventas es el que se debería usar?

**Comment by yasmanycastillo** [comment]
@gustavovalverde  que opinas de esto, colo un comentario de la DGII refiriendose a este tema.

•	Emisión de la factura: remitir la factura en el formato 606 correspondiente al periodo según la fecha de emisión de esta, eligiendo en la columna Forma de pago: compra a crédito. En este caso no debe completar los campos Fecha de Pago, Retención ITBIS, Tipo de Retención y Monto Retención Renta.
•	Pago de la factura: reportar la factura nuevamente en el periodo correspondiente al pago de la misma, completando además los campos Fecha de Pago, Retención ITBIS, Tipo de Retención y Monto Retención Renta, de acuerdo a la retención realizada.

Formato 607

•  Emisión de la factura: remitir la factura en el formato 607 correspondiente al periodo según la fecha de emisión de esta, completando la columna venta a crédito. En este caso no debe completar los campos Fecha de Retención, Retención ITBIS, Retención Renta y las demás casillas referentes al medio de pago distintas a ventas a créditos.
•  Pago de la factura: reportar la factura nuevamente en el periodo correspondiente al pago de la misma, completando además los campos Fecha de Retención y Retención ITBIS o Retención Renta, de acuerdo a la retención realizada.

**Comment by gustavovalverde** [comment]
Hay una funcionalidad en Odoo para esto, que se llama "Impuesto con Base en el Efectivo", para que la retención se haga en el pago. 

A sinceridad no la utilizo (ni creo que vaya a hacerlo). Prefiero manejar eso al momento de la reportería más que al momento de la factura y el registro financiero.

De igual manera, la mayor parte de los casos es con proveedores informales, y en estos casos la retención se debe registrar al momento de que se hace la factura, ya que si es un informal y tú eres quien generas la factura, se supone que no la generarás antes de que te hagan el servicio; por lo cual no aplica tener que esperar hacerla al momento del pago.

**Comment by gustavovalverde** [comment]
@herohat para ventas, al momento de aplicar el pago, también puedes seleccionar que esa diferencia la envíe a una cuenta de retención; por lo que con Odoo por default se pueden hacer retenciones en el pago al momento de la venta.

**Comment by herohat** [comment]
@yasmanycastillo sobre ese comunicado, es así.  En la versión 10 de ODOO de los reportes fiscales que hice lo programe así y en la nueva versión de los reportes fiscales que estoy haciendo estoy justamente programando esa funcionalidad.

**Comment by herohat** [comment]
> @herohat para ventas, al momento de aplicar el pago, también puedes seleccionar que esa diferencia la envíe a una cuenta de retención; por lo que con Odoo por default se pueden hacer retenciones en el pago al momento de la venta.

@gustavovalverde el caso es que una entidad gubernamental te retiene el 5% de ISR y 30% del ITBIS, por lo tanto son 2 retenciones y ODOO por default al momento del pago solo me permite aplicar 1 retención.

**Comment by gustavovalverde** [comment]
@herohat Si registras el pago y lo haces por asignación de pagos (v11), puedes registrar la diferencia en dos cuentas diferentes.

**Comment by herohat** [comment]
@gustavovalverde como es eso de "asignación de pagos"? Dónde lo encuentro?

**Comment by gustavovalverde** [comment]
En los pagos, al momento de validar, sale un smart button arriba a la derecha

**Comment by yasmanycastillo** [comment]
@gustavovalverde entonces seguimos como hasta el momento, registrando las retenciones en la factura y solo hacemos dichos ajustes en la reporteria? A vez como indicas seria tambien solo usar la asignacion de pagos si desean retener al momento de pagar.

@herohat que opinas, segun lo explica no se necesitaria ajustar el flujo de pago, solo reporteria.

**Comment by herohat** [comment]
@yasmanycastillo pues si es como indica Gustavo, funcionaria muy bien así.

Lo demás de maneja en los reportes.

**Comment by herohat** [comment]
@gustavovalverde ayudame a entender lo de la asignación de pagos.   Estoy probando un ejemplo de una factura de 50 mil + ITIBS que le hago a la Superintendencia de Electricidad.   Entonces tenemos:

50 mil subtotal
9 mil ITBIS
Total de la factura: 59,000

Al momento del pago, el cliente solo me paga 53,800 pues me retuvo 30% del ITBIS (2,700) y 5% de ISR sobre los 50 mil, que son 2,500.

Entonces en ODOO me voy a Facturación -> Pagos - > Crear y allí registro el monto que me pago el cliente (53,800):

![image](https://user-images.githubusercontent.com/1145973/57142058-a6544b00-6d89-11e9-9b93-e998922cc4ab.png)

Le doy al botón Confirmar y entonces veo esta pantalla:

![image](https://user-images.githubusercontent.com/1145973/57142119-c7b53700-6d89-11e9-8463-49bed7609f17.png)

Luego le doy al botón "Asignación de Pagos" y entonces veo esta pantalla:

![image](https://user-images.githubusercontent.com/1145973/57142177-e7e4f600-6d89-11e9-853b-0185876c9c36.png)

Podrías darme un ejemplo de como registro las dos retenciones?
