### ISSUE TITLE
Modicar la creacion de contactos en base de datos multiempresa  que sean multilocalidades.

### ISSUE THREAD

**Issue by jpshort** [odoo-dominicana/l10n-dominicana#388]
#### Impacted versions
v12
#### Steps to reproduce
Crear un contacto en multiempresa y multi localidad.
Modificacaciones de las vistas si el pais no es dominicana
#### Current behavior
Al crear un contacto en una base de datos multiempresa y multilocalidad, si el numero de RNC/Cedula es igual a 9 presenta un error como si se trata de un codigo de la Rep Dominicana. Ademas muestra la sugerencia de contactos que hace el servicio a la DGII.

En contabilidad muestra en el menu de los informes los reportes dominicanos.

En la vista de contacto muestra los campos de RNC/CEDULA

#### Expected behavior
Que no haga validaciones si se cambia a una empresa con un pais diferente al de la localizacion Dominicana y que ademas no muestra las sugerencias de los contactos que se encuentran en la DGII.

Remove en los informes contables los relacionados a Dominicana del menu, cuando se encuentre en una empresa de otros pais.

En la vista de contacto, si la empresa no es Dominicana dejar el estandar de Odoo.

**Comment by akevinieron** [comment]
Tamo internacionales!!

**Comment by gustavovalverde** [comment]
Esto es todo un proyecto completo de que la localización sea multi-país / multi-localización. Este es solo 1 de los muchos casos que ahora generan incompatibilidad

**Comment by jlopezg** [comment]
Este caso fue corregido en versiones posteriores a la 12.0.
