### ISSUE TITLE
Eliminar la identificacion en factura de NCF de consumo que sobre pasan el limite, si la DGII lo aprueba 

### ISSUE THREAD

**Issue by jpshort** [odoo-dominicana/l10n-dominicana#389]
#### Impacted versions
v12
#### Steps to reproduce
Creacion de facturas con NFC de consumo que sobre pasan el limite requerido por la DGII

### Current behavior
Si una factura con NCF de para consumidor final, es igual o sobre pasa el limite requerido por la DGII, actualmente es 250,000, el sistema exige que se proporsiones una identificacion.

#### Expected behavior
Existen casos, en los cuales la DGII, si permite que no se requiera la identificacion, si sobre pasa el limite, uno de esos casos es cuando el cliente es una empresa extrajera, la DGII emite un documento aprobando dichas operaciones a las empresas con ventas al exterior.

Se podria colocar un cotejo en los clientes, para identicarlos y no mostrar el mensaje y que se pueda hacer la factura.

**Comment by gustavovalverde** [comment]
Me podrías pasar el argumento legal de esto @jpshort? Para hacer ese commit con esa base.

**Comment by gustavovalverde** [comment]
@jpshort, quedo en espera de la base legal.

**Comment by akevinieron** [comment]
@jpshort un recordatorio!!

**Comment by jpshort** [comment]
Hola @gustavovalverde, a que te refieres con argumentos legales, necesitas alguna imagen de una carta?

**Comment by jpshort** [comment]
@gustavovalverde el cliente tiene una autorizacion para eso, solo dime si necesitas eso.

**Comment by akevinieron** [comment]
@jpshort lo importante aquí sería saber si eso es algo particular de tu cliente o es algo que siempre se dará bajo las circunstancias especificas. En caso de no quedar claro o que solo afecte a particulares excepcionales entonces no tendría mucho sentido agregarlo en la localización dominicana.

**Comment by jeffryjdelarosa** [comment]
@jpshort la manera de emitir o generación de los NCFs están basado a las autorización de la DGII, cumpliendo con las normas y ya la ultima [Norma 05-19](https://dgii.gov.do/legislacion/normas/Documents/Norma05-19.pdf). 

Si a la personas a quien se va a vender sea un servicios o bienes debes utilizar una factura de consumo, y debes de colocar el ID de la empresa o persona. Y luego remitir esta información en el resumen de factura de consumo y también esas facturas superiores al limite en el 607.

Ahora bien si se refieres a las personas que están registrada en [CEIRD ](https://www.ceird.gob.do) y [ADOEXPO ](https://adoexpo.org) de lo cual lo único es para beneficiarse de la Tasa Cero de ITBIS. Pero no existe base legal que es lo que le solicita @gustavovalverde y @akevinieron para proceder con su requerimiento. 

Si existe una norma, ley o decreto que ampare dicho proceso , por favor compartirlo.

**Comment by jpshort** [comment]
@gustavovalverde 
@jeffryjdelarosa ya empece a gestionar con el cliente esos documentos, y de paso validar si existe una normativa interna para esos casos, lo que si te aseguro que eso esta dando mucho dolores de cabeza a los exportadore.

**Comment by jpshort** [comment]
@akevinieron eso no es un caso particular de mi cliente, es algo que compete a todo el que realiza exportaciones al exterior, ya que no usa un NCF para credito fiscal, pero si tienen una autorizacion de la DGII para tales casos

**Comment by gustavovalverde** [comment]
Este caso se estará cerrando por falta de los documentos que avalan el proceso; se estará rehabilitando cuando sean adjuntados.
