### ISSUE TITLE
Cuales printes fiscal esta certificado por la DGI

### ISSUE THREAD

**Issue by blfernandez** [odoo-dominicana/l10n-dominicana#396]
Favor de indicarme con cuales printer de los que la DGII indica esta certificado elmanejo de los NCF por ODOO y este plugin

**Comment by blfernandez** [comment]
las impresoras Bixolon estan homologada para Odoo

**Comment by akevinieron** [comment]
Ni odoo ni este módulo trabajan de manera directa con impresoras fiscales. Por lo general se utiliza una interfaz (intermediario) que sí este homologada con DGII.
