### ISSUE TITLE
ncf_manager: Handling of new NCF structure for Norma 06-18

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#4]
En este Issue se estarán llevando las diferentes opiniones de la comunidad de cómo debería llevarse a cabo la estructuración en Odoo de la nueva estructura de comprobantes y la metodología de la fecha de vencimiento.

![norma 06-18](https://user-images.githubusercontent.com/16890942/36076666-a1892748-0f35-11e8-8481-936f8d18178d.jpg)

**Comment by gustavovalverde** [comment]
@eneldoserrata @juhenriquez @yasmanycastillo, como que deberíamos iniciar a meterle lápiz a esto, de cómo vamos a implementarlo.

En Diciembre estuvimos reunidos @juhenriquez @yasmanycastillo @RafosRD, Victor y yo viendo un montón de formas de cómo hacer varios cambios en los shops del `ncf_manager`, y en ese momento todos llegamos a consenso de transferir los mismos a un notebook dentro de los diarios de venta, para el manejo de las secuencias, para que hubiese un diario por sucursal / caja (tendría flexibilidad para ambos niveles), y que este a su vez llevara todos los cambios de secuencias según el tipo de partner en el ir_sequence.

**Comment by gustavovalverde** [comment]
Ahora, como será una sola secuencia para el negocio completo (no habrá secuencia para sucursal o punto de venta), la solución parcial, que en teoría es _aceptable_, es que si a un negocio le entregan 10,000 secuencias; distribuiría de la 1-2,000 (a la sucursal 1) ---> 1-1,000 (caja 1) | 1,001 - 2,000 (caja 2); etc.

Por lo que el mismo concepto que armamos en diciembre puede ser funcional para estos fines.

**Comment by edsersolis** [comment]
No, recuerda que ellos buscan control mediante la secuencia. No puedes declarar la 1,001 sin antes haber declarado la 1,000.

De momento creo que no hay otra forma más que 100% en línea, o en su defecto un HA.

**Comment by gustavovalverde** [comment]
@edsersolis ya me confirmaron que esa será la forma, no hay de otra.

**Comment by eneldoserrata** [comment]
Me gusta la idea de que que en ves de shop el shop sea un diario con las secuencias de los diferentes tipos de secuencias

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gustavovalverde** [comment]
Ya esto fue implementado, solo se harán los test en #54 para ampliar alcance
