### ISSUE TITLE
Crear pantalla para mostrar las facturas al presionar el action button Consultar facturas

### ISSUE THREAD

**Issue by eneldoserrata** [odoo-dominicana/l10n-dominicana#40]
Confeccion pantalla

```javascript
var ClientListScreenWidget = ScreenWidget.extend({
    template: 'ClientListScreenWidget',
```

Registrar pantalla

```javascript
gui.define_screen({name:'clientlist', widget: ClientListScreenWidget});
```

Mostrar pantalla

```javascript
this.$('.set-customer').click(function(){
            self.gui.show_screen('clientlist');
        });
```

![odoo_pos-order.png](https://zube.io/files/odoo-dominicana/5b809b416556829d171d1f8aa06a2f71-odoo_pos-order.png)

**Comment by edsersolis** [comment]
Limitar a dos decimales el monto.

**Comment by eneldoserrata** [comment]
Lo de los decimales se hace a nivel de precision decimal en configuration de la moneda

**Comment by edsersolis** [comment]
Si pero por defecto no viene con tantos decimales como en el screenshot por eso lo menciono

**Comment by eneldoserrata** [comment]
Issue de prueba aprendizaje https://zube.io
