### ISSUE TITLE
ncf_pos: despues de cerrar la seesion la secuencia ncf aumenta al siguiente numero.

### ISSUE THREAD

**Issue by reneivanxd** [odoo-dominicana/l10n-dominicana#410]
#### Impacted versions
11.0
#### Steps to reproduce
Configurar el punto de venta para generar facturas automaticas con cada orden. abrir y cerrar una sesion de Punto de venta.
#### Current behavior
El numero siguiente de la secuenta de NCF se aumenta en 1. Esto esta causando el salto de secuencias.
#### Expected behavior
El numero no debiaria ser aumentado a cause del cierre de la session

**Comment by reneivanxd** [comment]
Setting
![Annotation 2019-06-18 215004](https://user-images.githubusercontent.com/1379868/59719143-9b5b5a00-9213-11e9-9817-2d0823f34ca3.png)

Last NCF used 277
![Annotation 2019-06-18 2150042](https://user-images.githubusercontent.com/1379868/59719171-b1691a80-9213-11e9-923a-1cbf2b6c39a9.PNG)

The next number should be 278 but after closing the session it went up to 279
![Annotation 2019-06-18 2150043](https://user-images.githubusercontent.com/1379868/59719210-ccd42580-9213-11e9-8ac1-e08f33f29f53.PNG)

**Comment by gustavovalverde** [comment]
Esto fue corregido hace un tiempo, pero no encontré el commit para referenciarlo aquí.
