### ISSUE TITLE
Odoo 12 Impresion de Facturas

### ISSUE THREAD

**Issue by blfernandez** [odoo-dominicana/l10n-dominicana#414]
#### Impacted versions
Odoo 12

Impresion de Facturas

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_with_payments_203
  File "<template>", line 2, in body_call_content_202
AttributeError: 'account.invoice' object has no attribute '_get_tax_amount_by_group'

Error to render compiling AST
AttributeError: 'account.invoice' object has no attribute '_get_tax_amount_by_group'
Template: account.report_invoice_document_with_payments
Path: /templates/t/t/div/div[3]/div/div/table/t[1]
Node: <t t-foreach="o._get_tax_amount_by_group()" t-as="amount_by_group">
                                        <tr style="border-bottom:1px solid #dddddd;">
                                            <t t-if="len(o.tax_line_ids) == 1 and o.amount_untaxed == amount_by_group[2]">
                                                <td>
                                                    <span t-esc="amount_by_group[0]"/>
                                                    <span>&amp;nbsp;<span>en</span>
                                                        <t t-esc="amount_by_group[4]"/>
                                                    </span>
                                                </td>
                                                <td class="text-right">
                                                    <span t-esc="amount_by_group[3]"/>
                                                </td>
                                            </t>
                                            <t t-else="">
                                                <td><span t-esc="amount_by_group[0]"/></td>
                                                <td class="text-right">
                                                    <span t-esc="amount_by_group[3]"/>
                                                </td>
                                            </t>
                                        </tr>
                                    </t>

**Comment by gustavovalverde** [comment]
Hola

¿Esto llegaste a corregirlo? No tenemos otros reportes similares; y hay cientas de instalaciones imprimiendo actualmente.

**Comment by jeffryjdelarosa** [comment]
@blfernandez Tienes problemas aun con este tema?
