### ISSUE TITLE
Comprobante máximo, no respetado en ncf_pos

### ISSUE THREAD

**Issue by juhenriquez** [odoo-dominicana/l10n-dominicana#420]
#### Impacted versions
V10, V11, v12
#### Steps to reproduce
Configurar un numero máximo en el diario de factura. Sobrepasar este numero. 
#### Current behavior
Sobrepasa el número máximo. 
#### Expected behavior
Le ponga un freno al usuario. Talvez tener casilla para override  en punto de ventas, para evitar conflictos en facturación.

**Comment by gustavovalverde** [comment]
Fixed 6a3991afecd489afee404601b124ccfddc2b752b
