### ISSUE TITLE
Devolver producto por PoS esta asignando B01 o B02 al hacer la rectificativa.

### ISSUE THREAD

**Issue by AxelPina** [odoo-dominicana/l10n-dominicana#424]
#### Impacted versions

Odoo 12

#### Steps to reproduce

1) Dirigirse a Punto de Venta> Pedidos > Pedidos.

2) Devolver productos & hacer nota de crédito.

Después, ir a la factura y en el campo de NCF `(reference)` deberá salir un B01 o B02.

#### Current behavior

Al hacer nota de credito por Punto de Venta le asigna B01 o B02.

#### Expected behavior

Debe de asignar B04 al hacer nota de crédito.

> P.S: También sucede que cuando se hace todo ese proceso, pero en la parte de "devolver productos" automáticamente toma que todos los productos serán devueltos, al editarlo, si la factura queda en positivo, ya sea porque la devolución es menos de lo que hizo la factura original, en vez de crearse una factura "rectificativa" se creara una factura de "consumo".

**Comment by gustavovalverde** [comment]
Hola @AxelPina pudiste solventar esto? Porque no pudo ser reproducido, y más bien parece ser un tema de configuración.

Cerraré el issue mientras tanto; si persiste me dejas saber por esta vía.
