### ISSUE TITLE
No logro instalar los módulos en la versión 12

### ISSUE THREAD

**Issue by odooscio** [odoo-dominicana/l10n-dominicana#443]

**Comment by MikeHiciano** [comment]
@odooscio que problema te esta presentando, o que error te esta dando?

**Comment by odooscio** [comment]
No me da error en si, se actualiza la pagina y cuando vuelvo a ver el modulo me dice cancelar instalacion

**Comment by odooscio** [comment]
> @odooscio que problema te esta presentando, o que error te esta dando?

No me da error en si, se actualiza la pagina y cuando vuelvo a ver el modulo me dice cancelar instalacion

**Comment by MikeHiciano** [comment]
> > @odooscio que problema te esta presentando, o que error te esta dando?
> 
> No me da error en si, se actualiza la pagina y cuando vuelvo a ver el modulo me dice cancelar instalacion

@odooscio eso es que algo se esta colgando en backend, de casualidad instalaste el requirements.txt?

independientemente de eso, revisa los logs a ver

**Comment by odooscio** [comment]
> > > @odooscio que problema te esta presentando, o que error te esta dando?
> > 
> > 
> > No me da error en si, se actualiza la pagina y cuando vuelvo a ver el modulo me dice cancelar instalacion
> 
> @odooscio eso es que algo se esta colgando en backend, de casualidad instalaste el requirements.txt?
> 
> independientemente de eso, revisa los logs a ver

La verdad lo instale el odoo desde git,  pero ahora inicie una instancia nueva sin datos demo para probar todo desde cero

**Comment by MikeHiciano** [comment]
@odooscio resolviste lo de la instalacion de los modulos?

**Comment by odooscio** [comment]
> @odooscio resolviste lo de la instalacion de los modulos?

No hermano ahora los subo a la carpeta de extras y no me los reconoce ni aunque los cambie de ruta den el addons_path,

**Comment by odooscio** [comment]
> @odooscio resolviste lo de la instalacion de los modulos?

Me ayudas hermano ?

**Comment by gustavovalverde** [comment]
@odooscio https://t.me/odoord

**Comment by odooscio** [comment]
Si señor pude resolver, gracias, ahora estoy probando la version 13 pero
aun no veo la localización dominicana para esta versión
