### ISSUE TITLE
POS: Notas de credito que cancelen la factura

### ISSUE THREAD

**Issue by raulovallet** [odoo-dominicana/l10n-dominicana#464]
Crear un botón que estará al lado del botón "return" (ver archivo adjunto) para esta funcionalidad.

<img width="1118" alt="Screen Shot 2019-11-08 at 10 11 18 AM" src="https://user-images.githubusercontent.com/23384474/68496809-067bec00-0208-11ea-9570-49aafb8de7fb.png">

Estas notas de crédito deben cancelar los pagos vinculados a esa factura y conciliar la nota de crédito con dicha factura.

Esto solo aplica a facturas que no tengan notas de crédito vinculadas como un pago o facturas que tengan notas de crédito realizadas.

**Comment by jlopezg** [comment]
@raulovallet esto se hizo?
