### ISSUE TITLE
ncf_manager: Changes needed in Odoo's invoice template to comply with Norma 06-18

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#5]
#### Impacted versions:
11.0

#### Steps to reproduce:
Crear una factura
Imprimirla (por backend o por POS)

#### Current behavior:
La factura no tiene el formato correspondiente que será utilizado con la Norma 06-18

#### Expected behavior:
Desde ya este formato debe ir cambiando para cumplir con la norma, y solo sea necesario agregar la fecha de vencimiento.

#### Video/Screenshot link (optional):
En teoría, según panel llevado a cabo por la DGII, este es el draft inicial del diseño según lo que especifica la norma:

![image](https://user-images.githubusercontent.com/16890942/36076714-4cfc1748-0f36-11e8-8ac3-0462f873511a.png)

**Comment by eneldoserrata** [comment]
Ese formato siempre lo han publicado; entiendo que no tiene que ser identica a esa (que esta bien fea) lo importante es que tenga los campos que esta muestra.

**Comment by edsersolis** [comment]
@eneldoserrata según tengo entendido el diseño no debe ser igual mas el formato si; dígase, la ubicación de los datos del cliente, la ubicación de los datos de la empresa.

Por otro lado se debe mostrar el subtotal de los montos exentos y otro de los gravados (tremenda estupidez pero bien).

Entiendo que la parte de ITBIS podemos dejarla como ya la tenemos en Odoo, que no se muestre ese 18% dado que hay otros porcentajes de ITBIS. Lo que si debemos ajustar es que el catálogo de impuestos muestre el tag "E" para los exentos, y me parece que los que están gravados llevan una "I".

Válido esto (si aparece información) y les dejo saber.

**Comment by edsersolis** [comment]
**Tomado de la Norma 06-18, Sección III referente a Formatos**

> **Artículo 7.** Formato de Comprobante. Los requisitos y características del comprobante indicado
> en el artículo 7 del Decreto nº 254-06 deben presentarse en el formato único y obligatorio de la
> manera siguiente:
> 
> **Encabezado**
> En la parte superior del encabezado, lado derecho del documento, deben estar contenidas las
> siguientes informaciones:
> 
> a) Denominación del tipo de comprobante fiscal según corresponda, de acuerdo a la
> clasificación establecida en el Artículo 4 del Decreto nº 254-06. Deberá identificarse si el
> documento emitido corresponde a un comprobante para consumidor final o con valor fiscal,
> conforme lo dispuesto en el Artículo 2 de la presente Norma General.
> b) Número secuencial de comprobante fiscal autorizado por la DGII.
> c) Fecha del vencimiento del número de la secuencia. Este requisito sólo aplicará para los
> comprobantes con valor fiscal.
> 
> En los casos de comprobantes fiscales de nota de crédito o débito, adicionalmente debe indicarse
> el número secuencial del comprobante fiscal modificado por la nota correspondiente.
> 
> En la parte superior del encabezado, lado izquierdo del documento, deben estar contenidas las
> siguientes informaciones:
> a) Número de Registro Nacional de Contribuyente (RNC)
> b) Nombre o Razón Social del emisor como consta en el Registro Nacional de Contribuyentes
> (RNC)
> c) Nombre Comercial del emisor si lo hubiera
> d) Punto de emisión (Sucursal)
> e) Fecha de emisión
> 
> En la parte inferior del encabezado, lado izquierdo, la factura debe contener los datos del cliente o
> destinatario:
> a) Número de Registro Nacional de Contribuyente
> b) Nombre o Razón Social como consta en el Registro Nacional de Contribuyentes
> 
> **Parte central**
> En la parte central el documento debe contener los datos indicados en el artículo 8 del Decreto nº
> 254-06, según el bien o servicio transado.
> 
> **Parte final**
> En la parte final del documento debe incluirse los datos de quien imprime los comprobantes
> fiscales (en caso de que sea distinto de quien los emite) y el destino. Es decir, si se trata de la
> original o la copia.
> 
> **Párrafo I.** La DGII pondrá a disposición del público en general, la representación impresa del
> documento descrito en el presente artículo. Además, podrá actualizar dicha representación
> mediante su publicación en los medios de comunicación general, incluyendo los medios digitales,
> con al menos dos meses de anticipación a la fecha en que se requieran.
> 
> **Párrafo II.** El comprobante que acredita la transacción deberá ser entregado al consumidor del
> bien o servicio, y la copia o duplicado deberá ser conservada, conforme lo dispuesto en el literal
> h) del artículo 50 del Código Tributario.
> 
> **Artículo 8.** Disposiciones especiales para contribuyentes con soluciones fiscales. Los
> contribuyentes con soluciones fiscales deben utilizar el formato de comprobante predefinido por
> la DGII para este dispositivo

**Comment by edsersolis** [comment]
De la parte de los impuestos no dice nada. Sin embargo creo que los exentos podemos ponerle E y a los de ITBIS su porcentaje (18%, 16%) según corresponda de modo tal que en la impresión de tickets del POS también se vean de esta manera, aprovechando mejor el espacio y manteniendo homogeneidad entre este y el backend.

**Comment by gustavovalverde** [comment]
En las facturas E es para exentos y G para grabados.

**Comment by gustavovalverde** [comment]
¿Quién diseñará los templates de las facturas nuevas? (basada en las de Odoo, claro) @yasmanycastillo @eneldoserrata @RafosRD @jlopezg 

Yo no soy muy bueno con las vistas.

**Comment by gustavovalverde** [comment]
@yasmanycastillo podría darle un ojo al ticket actual del POS? En comparación con el anterior perdió mucho formato y los temas que tienen que ver con impresora fiscal no deben ir en este ticket cc: @eneldoserrata @akevinieron

**Comment by gustavovalverde** [comment]
Ahora que me fijo, el formato que se utilizó fue el de impresora fiscal, pero el que nos corresponde es el de handheld:

http://dgii.gov.do/contribuyentes/personasFisicas/inicioOperaciones/ComprobantesFiscales/Documents/FacturaHandhel.pdf
