### ISSUE TITLE
Crear factura automaticamente al momento de hacer un pedido

### ISSUE THREAD

**Issue by eneldoserrata** [odoo-dominicana/l10n-dominicana#55]

**Comment by edsersolis** [comment]
Esto debe ser parametrizable. No todas las empresas ocupan que se genere la factura tan pronto se hace el pedido.

**Comment by edsersolis** [comment]
Ahora veo que es en el POS. Ahí entiendo que esta bien que sea automática. :thumbsup:

**Comment by eneldoserrata** [comment]
Done on merge #56
