### ISSUE TITLE
Asignar cliente por default para la modalidad facturar en el POS

### ISSUE THREAD

**Issue by eneldoserrata** [odoo-dominicana/l10n-dominicana#57]
al activar la opcion facturar en la configuracion del POS este debe permitir configrar un cliente por defecto.

**Comment by akevinieron** [comment]
Entonces, segun entiendo, el modulo deberia crear este cliente nuevo y asignarlo por defecto a las facturas. 
 Preguntas:
1. Deberia haber una opcion de configuracion que permita cambiar este cliente por defecto?
2. En luagr de hacer un cliente Read Only y que no se pueda borrar, no seria mas sano ponerle mensajes de alertas cuando se intente modificar o eliminar dicho cliente??

**Comment by gustavovalverde** [comment]
@akevinieron 
1- Sí, en la configuración del POS debería haber una opción para estos fines.
2- Puede ser una opción, pero dejo que @eneldoserrata decida sobre eso.

**Comment by eneldoserrata** [comment]
merge [ref #59]
