### ISSUE TITLE
Secuencia NCF

### ISSUE THREAD

**Issue by Toxiostek** [odoo-dominicana/l10n-dominicana#575]
### Current behavior

Las secuencias del NCF se generan de 2 en 2.

EJ: Si pongo B0100000001 es el próximo número, el genera **B0100000002** luego **B0100000004** y **B0100000006**

**Comment by jeffryjdelarosa** [comment]
muestra como tienes configurado los NCF @Toxiostek

**Comment by jeffryjdelarosa** [comment]
@Toxiostek alguna Novedad?

**Comment by Toxiostek** [comment]
Me dijeron en un grupo de odoo @jeffryjdelarosa que debo tener una linea sin NCF para pero aun asi  siguió dando problema.
![errorNCFodoo](https://user-images.githubusercontent.com/53269904/75933431-5da96a80-5e50-11ea-9a32-a65bc8f66601.PNG)

**Comment by jeffryjdelarosa** [comment]
Escribime en telegram en privado https://t.me/jeffryjdelarosa para ver como te puedo ayudar..

**Comment by jeffryjdelarosa** [comment]
Resuelto @Toxiostek ?
