### ISSUE TITLE
Secuencia NCF, y Retenciones

### ISSUE THREAD

**Issue by armandorg81** [odoo-dominicana/l10n-dominicana#578]
Tengo 3 impuestos:
1. 18% ITBIS
2. 10% ITBIS
3. 100% ITBIS
Los 3 impuestos están configurados de la manera siguiente en las siguientes partes:
Grupo de impuestos para las dos retenciones:
2. 3. = Retenciones
Grupo de impuesto para el impuesto:
1. = ITBIS
Etiquetas de las dos retenciones:
1. R-ISR 10%
2. R-ITBIS 18%
Etiquetas del impuesto:
C-ITBIS 18%
 
El primer problema radica que cuando selecciono estos 3 impuestos en la factura con el tipo de comprobante Informal pues me dice que debo retener el 100% del itbis pero ya lo tengo retenido, no entiendo porque el mensaje.
Entonces al darle a validar me consume un numero de comprobante Informal sin estar confirmada la factura porque como explique mas arriba me dijo que tenia que Retener el 100% del ITBIS.

**Comment by jlopezg** [comment]
@armandorg81 podrías suministrar la información bajo la siguiente estructura?

**Impacted versions**
**Steps to reproduce**
**Current behavior**
**Expected behavior**
**Screenshot (required)**

**Comment by armandorg81** [comment]
Ya el error no lo puedo reproducir, así que pienso que era bug o algo estaba haciendo mal.
