### ISSUE TITLE
[ncf_manager] No funciona en compras

### ISSUE THREAD

**Issue by edsersolis** [odoo-dominicana/l10n-dominicana#62]
La creación de contactos debe igualarse a la de Ventas (eliminar el quick create).

Por otro lado, los campos: Diario, NCF ni Tipo de Gasto se están mostrando.

**Comment by gustavovalverde** [comment]
Esos campos no se muestran porque no está instalado el módulo de finanzas pro defecto. Creo que en dado caso tendríamos que cambiar la dependencia del ncf_manager

**Comment by yasmanycastillo** [comment]
Enterado,  verificare lo que has dicho @gustavovalverde sobre la dependencia.

**Comment by yasmanycastillo** [comment]
Para que los campos se muestren se debe especificar que el diario de Facturas Proveedor es tipo Compras Fiscales y que valide con DGII.
