### ISSUE TITLE
Errores al aplicar una nota de debito

### ISSUE THREAD

**Issue by OverloadSolutions** [odoo-dominicana/l10n-dominicana#626]
V12

Contabilidad ->Clientes -> Facturas -> (Selecionamos una factura) -> Aplicar NC o ND -> Nota de Debito

1- Cuando le damos clic a (Aplicar NC o ND) y seleccionamos Notas de Debito Dice : Fecha de Notas de crédito. (Fotos y Videos Agregados)

2- Cuando generamos una nota de débito y la imprimo me sale como factura y no dice a que factura afecto la nota de débito. (Fotos y Videos Agregados)

3- Cuando vamos a Contabilidad ->Clientes -> (NO EXISTE NOTA DE DEBITO) solo esta notas de credito.(Fotos y Videos Agregados)
 
https://youtu.be/bqUZl-vPKaM

![Nota de debito error 1](https://user-images.githubusercontent.com/58402409/81579947-cc3c0480-937a-11ea-8cbd-870aeffc4f3d.PNG)

![Nota de debito error 2](https://user-images.githubusercontent.com/58402409/81579936-c6deba00-937a-11ea-9d23-8cc2ed331f23.PNG)

![Nota de debito error 3](https://user-images.githubusercontent.com/58402409/81580640-b24ef180-937b-11ea-82ea-ed3b035b0da0.PNG)

**Comment by jlopezg** [comment]
Corregido en #704
