### ISSUE TITLE
Caracteres_TicketTPV

### ISSUE THREAD

**Issue by rreyes2** [odoo-dominicana/l10n-dominicana#631]
#### Impacted versions
Version 12-pro
#### Steps to reproduce
Go to TPV and try to generate the TPV ticket

#### Current behavior
Appear the 'test:true' label when it showed the company name. 

#### Expected behavior
That no show this ' test:true' label
![Errorticket](https://user-images.githubusercontent.com/38866814/84154529-3b1d8380-aa35-11ea-850f-a4aca3a9b1fe.png)

**Comment by jlopezg** [comment]
Estoy cerrando este issue pues el branch 12.0-pro ya no está en este repositorio.
