### ISSUE TITLE
Missing Dependancy

### ISSUE THREAD

**Issue by juhenriquez** [odoo-dominicana/l10n-dominicana#640]
Type: General

**Describe the bug**
Odoo Version: v13-xmart-ro
Missing dependancy for l10_do_pos: pos_orders_history_return

**Steps to Reproduce**
Try to Install l10_do_pos

**Expected behavior**
Install

**Additional context and screenshots**
[Add any other information such as screenshots, videos, messages]

![image](https://user-images.githubusercontent.com/8250019/84979095-9407ae80-b0fc-11ea-877b-894814897695.png)

**Configuration information**
Operating System:
Python version:

@raulovallet

**Comment by raulovallet** [comment]
solved
