### ISSUE TITLE
Fiscal Position for Special Regimes

### ISSUE THREAD

**Issue by juhenriquez** [odoo-dominicana/l10n-dominicana#642]
**Describe the bug**
Odoo Version: 
13.0

**Steps to Reproduce**
When Generating Invoice on Client Marked as Excempt, Invoice picks correct document type, but Fiscal Position is not set to special regime, which doesn't reflect Tax Exemptions for client.

**Expected behavior**
Select Special Regime fiscal position.

**Comment by jlopezg** [comment]
Esto fue corregido o no se pudo reproducir.
