### ISSUE TITLE
[Odoo 13] Aplicar retención al momento del pago

### ISSUE THREAD

**Issue by pdeoleo** [odoo-dominicana/l10n-dominicana#653]
Saludos, ¿cómo se puede hacer que en los reportes se muestre que la retención de una factura fue hecha al momento del pago, en vez de que aparezca la fecha de la factura?

Ya revisé vi el issue #384 que trataba el mismo tema, pero esto está relacionado al módulo nfc_manager, el cual no está en la versión 13, sino en anteriores. Me gustaría saber qué aplica en Odoo 13 con respecto a este tema.

Muchas gracias de antemano.

**Comment by jlopezg** [comment]
Saludos @pdeoleo 

Para que en los reportes se muestren las retenciones en la fecha del pago debe retener en el pago y/o asiento contable.

Considerando que su duda es sobre una funcionalidad de Odoo, y no directamente de la localización fiscal, estoy cerrando este issue.
