### ISSUE TITLE
Secuencia de NCF desaparece en POS

### ISSUE THREAD

**Issue by dg18** [odoo-dominicana/l10n-dominicana#661]
Type: General

**Describe the bug**
Odoo Version: v12 CE
Al momento de utilizar la función "All Invoices / Todas las Facturas" en el POS podemos ver el listado de pedidos/órdenes de POS/TPV como es normal, existe una columna llamada número de factura, he visto que coloca el valor de la secuencia de NCF correspondiente al pedido. Esto es normal. Ahora bien al momento de actualizar (F5) la página con la sesión de POS o cerrarla y volver a entrar, los valores cambian por el número de factura en vez del NCF. Esto inclusive causa que al momento de realizar devoluciones/NC el valor que tome sea el renderizado en esa vista en vez de order.ncf

**Steps to Reproduce**

1. Instale una nueva instancia con Odoo v12 CE.
2. Descargue el último commit correspondiente a 12.0 de la l10n-dominicana.
3. Haga las configuraciones de lugar, solo instalando Facturación/Contabilidad y POS junto a sus aplicaciones necesarias.
4. Proceda a iniciar su sesión de POS.
5. Realice la facturación de un pedido.
6. Ingrese a "All Invoices / Todas las Facturas".
7. Verá que al momento todo se comporta de forma esperada y correcta.
8. Actualice la página y verá el cambio ahora el campo ha tomado otro valor distinto (01).

Si fue un cliente de consumo sería B0200000001 el valor adecuado, ahora pasa a ser 01, por ejemplo. Pero se puede validar en Punto de Venta > Pedidos > Pedidos que mantiene consistencia con los valores, igualmente en las Facturas de cliente en el módulo de Facturación.

**Consideraciones**
Sobre los pasos a reproducir:

- En el punto 1, he realizado pruebas tanto con instalaciones "paso a paso, manual", como también con el uso de scripts, en todas he tenido el mismo comportamiento y resultado final. He estado utilizando especificamente este: https://github.com/Yenthe666/InstallScript/blob/12.0/odoo_install.sh para fines de la instalación de Odoo.
- En el punto 2, he estado haciendolo de la siguiente manera: Lo estoy tomando con: git clone --single-branch --branch 12.0 https://github.com/odoo-dominicana/l10n-dominicana.git

**Expected behavior**
Las secuencias de NCF debe de mantenerse en la vista y tener consistencia con los valores. El campo no debe de poblarse con un valor distinto a la secuencia de NCF de la orden/pedido.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/17618843/91329217-e49f2600-e795-11ea-982a-bb5d218ce0d3.png)
_Antes de recargar la vista._

![image](https://user-images.githubusercontent.com/17618843/91329333-09939900-e796-11ea-9fd3-2a748f093ab2.png)
_Después de recargar la vista._

![image](https://user-images.githubusercontent.com/17618843/91329082-b91c3b80-e795-11ea-9949-8d7b774417cb.png)
_Imagen del pedido haciendo referencia al comportamiento, para evidenciar el último punto._

![image](https://user-images.githubusercontent.com/17618843/91329522-3e9feb80-e796-11ea-9854-c404b06c1e66.png)
_Imagen de un ambiente productivo con el bug, esto para ilustrar._

**Configuration information**
Operating System: Ubuntu 18.04 LTS
Python version:

**Comment by jlopezg** [comment]
@akevinieron viste esto ya?

**Comment by dg18** [comment]
@akevinieron déjame saber si hace falta alguna aclaración más en este issue o el #662 y #663.

Saludos,

**Comment by akevinieron** [comment]
Hey, estoy de vuelta! @dg18 se ve bien documentado, gracias por tomarte el tiempo. Voy a revisarlo esta noche!

**Comment by raulovallet** [comment]
solve with: https://github.com/odoo-dominicana/l10n-dominicana/commit/0e37b28cd9075251835d25684dd635e1e489c2d1
