### ISSUE TITLE
NCF Afectado en NC no es el valor de secuencia correspondiente

### ISSUE THREAD

**Issue by dg18** [odoo-dominicana/l10n-dominicana#662]
Va de la mano con el issue #661 

Type: General

**Describe the bug**
Odoo Version: v12 CE
Al momento de realizar una "Devolución / NC" desde el POS, en una orden/pedido de los que aparecen listados en la vista "Todas las Facturas / All Invoices", al completar el proceso de la NC el recibo sale impreso pero el valor de NCF Modificado es tomado del valor renderizado en la vista. En vez de tomar la secuencia que le corresponde. Ejemplo: Si el valor de secuencia de NCF asignado para esa orden/pedido/factura es B0200000001 esta tomando 0002 o 01, todo acorde a como se tengan las sencuencias configuradas. Esto acorde a como se explica en el issue #661 si la NC no es hecha en la misma sesión activa sin salir ni recargar la vista.

**Steps to Reproduce**
1. Inicie su sesión de POS.
2. Vaya a "All Invoices / Todas las Facturas".
3. Dirijase a una de sus facturas ya realizadas en el ambiente de laboratorio.
4. Seleccione una, preferible de las que presentan el inconveniente reportado en #661 
5. Realice el paso a paso para una devolución.
6. Revisar el voucher / recibo (pos receipt) emitido en el campo NCF Modificado (afectado).

**Consideraciones**
Este bug se esta presentando tanto en el POS al momento de una devolución / NC, como también en el backend, si se intenta realizar presenta el mismo comportamiento anómalo. Tener en consideración como se describe en el issue #661 realizar en la misma instancia de laboratorio, para poder conseguir reproducir el comportamiento.

**Expected behavior**
El campo de NCF Modificado usado en el recibo generado siempre debe de ser el NCF de origen afectado, no el valor renderizado de la vista. Debe de validarse la secuencia y estructura de la misma.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/17618843/91329082-b91c3b80-e795-11ea-9949-8d7b774417cb.png)
_Imagen del pedido haciendo referencia al comportamiento._

![image](https://user-images.githubusercontent.com/17618843/91340885-b413b800-e7a6-11ea-8dea-c880deaa7373.png)
_Imagen del vocuher emitido, se evidencia el NCF Modificado._

**Configuration information**
Operating System: Ubuntu 18.04 LTS
Python version:

**Comment by raulovallet** [comment]
solve https://github.com/odoo-dominicana/l10n-dominicana/commit/0e37b28cd9075251835d25684dd635e1e489c2d1
