### ISSUE TITLE
Error de conciliación al utilizar más de una vez una misma NC

### ISSUE THREAD

**Issue by dg18** [odoo-dominicana/l10n-dominicana#663]
Type: General

**Describe the bug**
Odoo Version: v12 CE
En el POS se permite realizar el uso de una NC siempre y cuando esta tenga un remanente y se encuentre en el tiempo disponible acorde a la configuración de POS. Esto es un error por los NCF no son reutilizables en si mismos, luego de validados. Ocasionando con esto que el usuario final pueda cometer un error al momento de utilizarla como medio de pago.

**Steps to Reproduce**

1. Abrir una sesión de POS/TPV.
2. Realizar una venta/pedido. Asignado a un cliente particular.
3. Realizar una devolución de uno de los artículos o la órden completa.
4. Proceder a realizar una nueva orden/pedido de POS. Al mismo cliente del paso 2-3.
5. Seleccionar como método de pago nota de crédito.
6. Seleccionar del menú desplegable la nota de crédito correspondiente. En caso de que no aparezca, recargar.
7. Proceder a validar la orden.
8. Verificar el recibo emitido.
9. Proceder a crear una nueva orden/pedido con el mismo cliente seleccionado.
10. Seleccionar como método de pago para la orden una nota de crédito y tomar la misma ya utilizada previamente.
11. Completar el monto faltante (si aplica) con cualquier método disponible a elección.
12. Validar y verificar el recibo emitido.
13. Ver el error obtenido.

**Consideraciones**
El valor (monto) de la NC debe de ser mayor al total de la orden/pedido con la que será usada. Esto para poder tener un remanente en la misma.

**Expected behavior**
La NC luego de empleada no debería de permitir el utilizarla de nuevo, aunque la misma cuente con un fondo remanente (no utilizado), pero si debería de informar que cuenta con un monto y el valor de dicho monto. Esto último para fines de control.

No debería de emitirse un recibo (pos receipt) con una NC reutilizada, debe de existir algún tipo de validación para ello.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/17618843/91381376-404ccc00-e7f5-11ea-8bca-2bb37b89d8fd.png)
_Acorde a lo indicado en el paso 6, se muestra acá y seleccionamos._

![image](https://user-images.githubusercontent.com/17618843/91381301-185d6880-e7f5-11ea-8008-5b5c8e5d1580.png)
_Acá se puede observar la operación con el método de pago NC y que producirá un balance pendiente de uso (remanente)._

![image](https://user-images.githubusercontent.com/17618843/91381509-928ded00-e7f5-11ea-822a-b965925dceb4.png)
_Luego de validar nos emite nuestro recibo. Utilice los datos de una de las compañías en res_partner_demo.xml_

![image](https://user-images.githubusercontent.com/17618843/91381797-38d9f280-e7f6-11ea-96e1-42d76c2691ce.png)
_Ahora procedemos con el paso 9, como es visible nos aparece la misma NC._

![image](https://user-images.githubusercontent.com/17618843/91381885-6a52be00-e7f6-11ea-8cf2-88587583b15a.png)
_Como se ilustra en la captura estamos emulando los pasos 10-11._

![image](https://user-images.githubusercontent.com/17618843/91382123-ffee4d80-e7f6-11ea-8254-eb1039df5207.png)
_Nos emite de forma correcta el recibo, mismo con todas las informaciones, mencionando el uso de una NC como método de pago._

![image](https://user-images.githubusercontent.com/17618843/91382201-2b713800-e7f7-11ea-9c13-d9721453c9d4.png)
_Error obtenido debido al bug reportado._

![image](https://user-images.githubusercontent.com/17618843/91382226-3fb53500-e7f7-11ea-99d0-a1c60335a03e.png)
_A esto me refería con que se quedan "colgadas / enganchadas" las órdenes/pedidos de POS/TPV._

![image](https://user-images.githubusercontent.com/17618843/91383173-7db35880-e7f9-11ea-8039-3f99a6fff252.png)
_Generando también el siguiente mensaje, debido a que no se han "sincronizado".

**Sample Code / Stack Trace**
[173.255.224.183-1598500516343.log](https://github.com/odoo-dominicana/l10n-dominicana/files/5133977/173.255.224.183-1598500516343.log)
_Archivo adjunto contiene el log completo junto con otro error. Paso a listar el traceback solamente más abajo._

[create_from_ui-response-xhr.txt](https://github.com/odoo-dominicana/l10n-dominicana/files/5133998/create_from_ui-response-xhr.txt)
_Al momento de abrirlo, hacerlo como un JSON, cambiando la extensión/formato._

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/ncf_pos/models/pos_order.py", line 158, in create_from_ui
    p_id)
  File "/odoo/odoo-server/addons/account/models/account_invoice.py", line 1116, in assign_outstanding_credit
    return self.register_payment(credit_aml)
  File "/odoo/odoo-server/addons/account/models/account_invoice.py", line 1103, in register_payment
    return (line_to_reconcile + payment_line).reconcile(writeoff_acc_id, writeoff_journal_id)
  File "/odoo/odoo-server/addons/account/models/account_move.py", line 1010, in reconcile
    self._check_reconcile_validity()
  File "/odoo/odoo-server/addons/account/models/account_move.py", line 995, in _check_reconcile_validity
    raise UserError(_('You are trying to reconcile some entries that are already reconciled.'))
odoo.exceptions.UserError: ('Está tratando de conciliar algunas facturas que ya han sido conciliadas. ', '')

**Configuration information**
Operating System: Ubuntu 18.04 LTS
Python version:

**Comment by akevinieron** [comment]
No pude encontrar información específica sobre este tema.

**¿No se debe utilizar una nota de crédito en más de una ocasión?** 

Para aclarar el posible issue y la duda colocaré el siguiente ejemplo: existe una NC de 1,000 pesos. Actualmente se permite pagar 1 factura de 600 pesos y luego pagar otra factura con los 400 restantes.

Alguien tiene alguna información sobre esto??

Nota: si existe dicha restricción posiblemente sea un problema existente en el backend también

**Comment by gustavovalverde** [comment]
@dg18 Una nota de crédito puede ser utilizado tantas veces sea necesaria. La primera factura genera el NCF de nota de crédito. Luego de esto la nota de crédito se convierte en un método de pago (como un bono) que se puede utilizar tantas veces sea necesario. Lo que sí se aplica en algunos comercios es una política de expiración.

**Comment by dg18** [comment]
@gustavovalverde es correcto lo que mencionas, no estoy mencionando ni diciendo lo contrario en mi reporte de bug. Favor dejenme saber si está interpretando eso @akevinieron, @gustavovalverde. Lo que si menciono es que permite seleccionarlo y sigue apareciendo al tener un remanente. El módulo hace una validación (por llamarlo de alguna forma una conciliación) de ese NCF y lanza un error al intentar utilizarlo de nuevo, cosa que no debe de suceder.

Lo que se debe de realizar es lo que mencionas _que sea utilizado como un bono, descuento_ y si algunos comercios manejan una política por lo general sobre cómo operan con las NC. Pero hasta donde tengo entendido y llega mi conocimiento no se puede utilizar directamente como método de pago una NC ya empleada aunque tenga un remanente disponible. Los NCF no son reusables. Lo ideal es que se utilice todo el disponible, cosa que no siempre es posible, queda en la institución manejar una política y un control para los balances y NC emitidas por cliente. Para ser aplicadas las que tengan balances disponibles como descuentos o bonos, como mencionas.

@akevinieron es correcto lo que menciona, pero lo mismo ocasiona un error, espero que lo mencionado más arriba pueda responder tu duda.

**Comment by akevinieron** [comment]
@dg18 El error al momento de reutilizar una NC como método de pago no debería suceder y es algo a revisar.

En cuanto a la re-utilización de la nota de crédito como método de pago, creo que sigue habiendo una confusión y es algo que podemos aclararlo un poco más.

La nota de crédito se emite con un NCF único. Cuando se utilice esa NC para pagar por primera vez en una fecha futura se estará haciendo referencia a esa NC (que ya tiene un NCF otorgado al momento de emisión). Si más adelante se vuelve a utilizar la misma NC como método de pago, no se estará "reusando" el NCF, porque a pesar de que se utilice para pagar en 2 o más ocasiones solo se estará emitiendo 1 sola vez.

En pocas palabras, la forma en la que está funcionando actualmente está correcto.

**Comment by dg18** [comment]
@akevinieron estoy de acuerdo en el planteamiento. Creo que lo que está generando confusión es el título que utilice para nombrar esta incidencia (bug).

No creo que como esté funcionando actualmente sea lo correcto, debido a que si fuese adecuado no se estuviese experimentando el error. Pero si, comprendo que se refiere al proceso como tal, a lo cual si estoy de acuerdo, esa forma es más certera pues le evita al usuario final tener que procesarlo como un descuento o bono, como estuvimos comentando antes.

Voy a cambiar el título para uno que pueda ser más acorde a lo que comentamos.

**Comment by dg18** [comment]
@akevinieron Déjame saber si pudiste ver las adecuaciones y mi comentario fue suficiente para responderte en este issue.

Saludos,

**Comment by raulovallet** [comment]
solve with https://github.com/odoo-dominicana/l10n-dominicana/pull/670
