### ISSUE TITLE
Serial genial que agregaran las reimpresiones..

### ISSUE THREAD

**Issue by TEAM-CODESIGN** [odoo-dominicana/l10n-dominicana#673]
**Describe your question**
[A clear and concise description of your question or what you want help with]

**What have you tried?**
[Have you already searched online? What solutions have you tried?]

**Additional context**
[Add any other information or screenshots that would help us provide you with a better answer]

**Comment by dg18** [comment]
@TEAM-CODESIGN  a qué te refieres con ¿Reimpresiones? ¿Desde POS? ¿El voucher/recibo?

**Comment by jlopezg** [comment]
Issue cerrado por falta de respuesta del autor.
