### ISSUE TITLE
No se produce salida de ítem en POS al pagar pedido con NC

### ISSUE THREAD

**Issue by dg18** [odoo-dominicana/l10n-dominicana#682]
Type: General

**Describe the bug**
Odoo Version: 12 CE
En el POS al momento de realizar un pedido y pagarlo con una NC (Nota de Crédito) como método de pago no se producen las salidades de los articulos del inventario. Esto aplicable a los ítems de tipo almacenable, que son los que deben de realizar esta acción.

**Steps to Reproduce**

**Expected behavior**
Se deberían de producir los movimientos de albarán en un pedido, independientemente de si el método de pago fue una nota de crédito u otro. Actualmente no se produce la salida.

**Additional context and screenshots**

**Sample Code / Stack Trace**

**Configuration information**
Operating System: Ubuntu 18.04 LTS
Python version:

**Comment by jlopezg** [comment]
Fixed on #675
