### ISSUE TITLE
Version de Imagen Docker de 13 a 14 Docker File

### ISSUE THREAD

**Issue by anyeloroy** [odoo-dominicana/l10n-dominicana#683]
Hola,

La idea seria cambiar el tag de la imagen 13.0 a 14.0 en el Dockerfile para el branch 14.0 del repositorio.

Antes:
FROM  gcr.io/iterativo/dockerdoo:13.0

Despues:
FROM  gcr.io/iterativo/dockerdoo:14.0

Saludos,

**Comment by jlopezg** [comment]
@anyeloroy esto se hará cuando se trabaje la versión 14.0
