### ISSUE TITLE
ncf_pos vistas no compatibles con version 11

### ISSUE THREAD

**Issue by yasmanycastillo** [odoo-dominicana/l10n-dominicana#7]
#### Impacted versions:
11.0

#### Steps to reproduce:
Instalar ncf_pos. Ir al POS -> Configuracion -> Terminal Punto de Venta.
Notaran que los campos usuales agregados por el ncf_pos no se vizualizan, tales como usuarios, y demas.

#### Current behavior:
Las vistas del ncf_pos no estan adaptadas a la nueva vizualizacion de la vista.

#### Expected behavior:
Todos los campos agregados por ncf_pos deben visualizarse.

#### Video/Screenshot link (optional):
![deepinscreenshot_20180211172754](https://user-images.githubusercontent.com/7638760/36078719-eecc29fe-0f50-11e8-8d7a-b63888ebfed5.png)

**Comment by gustavovalverde** [comment]
@yasmanycastillo verifica si en la versión que tienes estás después de este commit e187b407ef1df79d4c4d6b0267474ef27d09fefd  que es donde arreglo eso.
