### ISSUE TITLE
[NCF-POS] Hacer que la validacion de facturas mayor o igual a 50 mil pesos soporte multimonedas

### ISSUE THREAD

**Issue by akevinieron** [odoo-dominicana/l10n-dominicana#72]
#### Impacted versions:
v11.0 - develop

#### Steps to reproduce:
En el POS, con utilizando alguna otra moneda que no sea Pesos Dominicanos, no funciona la validacion de 50 mil pesos por factura consumidor final para clientes sin cedula ni los mensajes de error son correctos

#### Current behavior:
En el POS, utilizando Pesos Dominicanos como moneda, existe una validacion para las facturas mayores o igual a 50 mil pesos de tipo consumidor final para clientes sin cedula .

#### Expected behavior:
El mensaje de error debe tomar en cuenta la moneda configurada actualmente y la validacion debe tomar en cuenta la conversion de los 50 mil pesos a la moneda configurado

**Comment by eneldoserrata** [comment]
@akevinieron que hacemos con este?
