### ISSUE TITLE
AttributeError: module 'stdnum.do.rnc' has no attribute 'check_dgii'

### ISSUE THREAD

**Issue by herohat** [odoo-dominicana/l10n-dominicana#79]
#### Impacted versions:

En develop branch. 

#### Steps to reproduce:

Settings -> Companies -> Edit 

#### Current behavior:

Al poner el valor del campo: TIN (VAT), en el cual estamos colocando un RNC válido sale este error:

  File "/etc/odoo/l10n-dominicana/ncf_manager/models/res.py", line 57, in onchange_company_vat
    self.partner_id.validate_rnc_cedula(self.vat)
  File "/etc/odoo/l10n-dominicana/ncf_manager/models/res.py", line 143, in validate_rnc_cedula
    dgii_vals = rnc.check_dgii(number)
AttributeError: module 'stdnum.do.rnc' has no attribute 'check_dgii' 

![image](https://user-images.githubusercontent.com/1145973/37913616-5009d870-30e3-11e8-850f-ef3345dbbe00.png)

**Comment by yasmanycastillo** [comment]
Podrias ver que version de stdnum tienes instalada? Pues actualmente no me da ese error.

**Comment by herohat** [comment]
Listo, era mi versión de stdnum, tenía la 1.5 y requiere la 1.8.1.

Gracias.
