### ISSUE TITLE
[ncf-pos] Poder filtrar las facturas por cliente y por fecha

### ISSUE THREAD

**Issue by akevinieron** [odoo-dominicana/l10n-dominicana#84]
#### Current behavior:
Las factuas se buscan por numero de factura solamente

#### Expected behavior:
Se pueda filtar las facturas por cliente especifico y por fecha

**Comment by eneldoserrata** [comment]
Es obligatorio que el cliente lleve su factura para que el usuario la busque por el numero de forma tal que si el cliente no tiene la factura tenga que escalar a un empleado de mayor rango
