### ISSUE TITLE
Agregar tipo de bien a catalogo de cuenta

### ISSUE THREAD

**Issue by eneldoserrata** [odoo-dominicana/l10n-dominicana#86]
#### Impacted versions:
11.0

#### Steps to reproduce:
Al crear una factura de compra, salen todas las cuentas contables independientemente del tipo de bien.

#### Current behavior:
 Se pueden equivocar seleccionando el tipo de bien que corresponda a la cuenta contable, o viceversa.

#### Expected behavior:
Cuando se seleccione un tipo de bien, se filtren las cuentas contables que corresponden al mismo.

**Comment by akevinieron** [comment]
Que deberia hacer si no existe dicha configuración??

**Comment by yasmanycastillo** [comment]
@eneldoserrata @gustavovalverde Como puedo reproducir esto, para encargarme de este issue.

**Comment by jrodmaster** [comment]
@eneldoserrata  @gustavovalverde  La persona que recomendo esta mejora es companera mia en el lugar donde trabajo, me puedo reunir con ella para que hablemos mas detenidamente acerca de Issue y asi buscarle una solucion

**Comment by eneldoserrata** [comment]
@yasmanycastillo la ide es ponerle un domain al campo account_id de las lineas de productos para que solo liste las cuentas que se puedan usar:

Cerrare este issue ya que esto es posible a nivel de diario en developer mode el diario de da la opcion de espesificar que cuentas puede usa.


<img width="1236" alt="facturas_de_proveedor__dop__-_odoo" src="https://user-images.githubusercontent.com/360270/38692668-7c486b5a-3e52-11e8-9a68-198fc5aaddce.png">
