### ISSUE TITLE
[RFC] Feedback for bringing l10n-dominican to production state

### ISSUE THREAD

**Issue by gustavovalverde** [odoo-dominicana/l10n-dominicana#9]
Aquí se recopilarán los comentarios de la comunidad para llevar el repositorio a producción en las próximas semanas.

Todos están invitados a hacer pruebas y comentar sobre el resultado de las mismas, crear los issues que encuentren y formular mejoras en este documento de retroalimentación.

**Comment by eneldoserrata** [comment]
Felicidades @gustavovalverde excelente trabajo, definitivamente nuestra comunidad pasara a otro nivel cuando nos terminemos de montar en este esquema de colaboracion, sugiero propongas una charla puede ser en linea para que nos hables de la estructura y de como debemos aplicarla.

**Comment by eneldoserrata** [comment]
Considero que el primer paso antes de publicar este repo publico en la comunidad debemos completar las siguientes tareas:

1-hacer un primer release estable
2-Documentar en el README Politicas de uso del repositorio.
3-Documentar por modulo en el README Instalacion y configuracion.

Y de esta forma garantizar una buena experiencia de usuario a la primera.

**Comment by yasmanycastillo** [comment]
A la vez antes del release estable seria bueno que ya tengamos todas las secuecias y las validaciones internas, externas trabajando, para asi poder ahorrar tiempo y evitar inconvenientes. 

Veo muy bien documentar cada modulo para explicar como configurarlo y usarlo correctamente. Vamos por buen camino.

**Comment by gustavovalverde** [comment]
@yasmanycastillo @edsersolis @juhenriquez @RafosRD pueden ayudar a hacer testing en esta primera etapa pre-publicación

**Comment by gustavovalverde** [comment]
Ah y don documentación @miguel-tavarez

**Comment by yasmanycastillo** [comment]
Por supuesto sacare un rato para eso esta tarde y te dejo saber.

**Comment by gustavovalverde** [comment]
Para la documentación: https://stackedit.io/app

**Comment by gustavovalverde** [comment]
@yasmanycastillo instálale este a la joven también porfa, en otra instancia para que vaya haciendo pruebas funcionales, que este es el que vamos a terminar utilizando. (aquí es solo facturación)

**Comment by yasmanycastillo** [comment]
@gustavovalverde entendido, hare eso esta misma noche para que mañana Giselly comience a probar.

**Comment by eneldoserrata** [comment]
Se ha creado un canal en slack para los developers de Odoo Dominicana solo estaran permitidos developer y tester.

https://marcoson.slack.com/messages/C99CU3FGA/

**Comment by gustavovalverde** [comment]
@daniboy2215 también se estará uniendo al testing de este repo

**Comment by gustavovalverde** [comment]
@juhenriquez @RafosRD 👀

**Comment by edsersolis** [comment]
@eneldoserrata pero ni tu estas en el grupo. Solo @juhenriquez y yo :facepunch:

**Comment by eneldoserrata** [comment]
Lo del grupo no se dio ahora estamos probando https://gitter.im/odoo_dominicana/l10n-dominicana?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by gustavovalverde** [comment]
Solo para actualizarnos, lo único de la base que viene faltando es la validación de los NCF con el servicio de stdnum. Luego de ahí estamos ready para avanzar con el tema de las secuencias.

**Comment by gustavovalverde** [comment]
@juhenriquez y @RafosRD, no los siento.

**Comment by gustavovalverde** [comment]
Este issue será cerrado, y se crearán issues específicos para cada prueba que se vaya a realizar.
