### ISSUE TITLE
The VAT number [131071422] for partner [SOFTNET TEAM SRL] does not seem to be valid.

### ISSUE THREAD

**Issue by herohat** [odoo-dominicana/l10n-dominicana#94]
#### Impacted versions:

10.0

#### Steps to reproduce:

Settings -> Company -> YourCompany

#### Current behavior:

Al poner el valor del campo:  Tax ID, me trae el nombre de la empresa automáticamente pero al intentar grabar obtengo el mensaje:

The VAT number [131071422] for partner [SOFTNET TEAM SRL] does not seem to be valid. 
Note: the expected format is 'CC##' (CC=Country Code, ##=VAT Number)

#### Expected behavior:

Grabar correctamente. 

#### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/1145973/38273887-1b2d93b6-375b-11e8-927e-4360faff0997.png)

**Comment by edsersolis** [comment]
Al parecer tienes un modulo de validación de VAT instalado lo que no debes para RD.

**Comment by herohat** [comment]
Revisando más a fondo el problema, note que efectivamente como dijo @edsersolis tengo una extensión que esta validando VAT, está es:  base_vat 

![image](https://user-images.githubusercontent.com/1145973/38279641-30e753b8-376f-11e8-9708-6302bba70973.png)

El problema es que yo no la instale, al menos no directamente, quien la instalo fue NCF MANAGER pues en sus dependencias tiene:

![image](https://user-images.githubusercontent.com/1145973/38279679-56595cf4-376f-11e8-8ecb-3376f0ab6031.png)

Y si intento removar esa extensión, me remueve el NCF manager.


![image](https://user-images.githubusercontent.com/1145973/38279695-72867cfe-376f-11e8-8d26-ef31beb9df73.png)

**Comment by gustavovalverde** [comment]
Wow, me parece que tendré que hacer un PR a Odoo, porque el campo VAT en la v10 realmente está en ese módulo, sin ese módulo el partner no tiene campo VAT; lo que quiero es evitarme crear un campo VAT con la localización si ya Odoo tiene uno.

**Comment by herohat** [comment]
@gustavovalverde  note que si le pones el prefijo del país, ejemplo:  DO131071422 pasa bien.   Si ese es el caso, sería evaluar entre hacer el PR a ODOO como comentas o en NCF MANAGER limpiar el DO del VAT.

**Comment by gustavovalverde** [comment]
Sí, es una posibilidad

**Comment by gustavovalverde** [comment]
Fixed by ac86b9606f821012e9a92ab38148470adf0b1c79
