### ISSUE TITLE
Debe configurar los NCF para este diario.

### ISSUE THREAD

**Issue by herohat** [odoo-dominicana/l10n-dominicana#95]
#### Impacted versions:

10.0

#### Steps to reproduce:

Configurar el diario "Customer Invoice", ver fotos de la configuración:

![image](https://user-images.githubusercontent.com/1145973/38279132-ecbe0134-376c-11e8-91ea-33ed8c66de4b.png)

![image](https://user-images.githubusercontent.com/1145973/38279147-fb4e97f4-376c-11e8-99a8-47400ff02f40.png)

Configurar la secuencia para ese diario, ver foto:

![image](https://user-images.githubusercontent.com/1145973/38279220-40e6546e-376d-11e8-94ee-9016c95600de.png)

Al darle validar a la factura, sale este mensaje, ver foto:

![image](https://user-images.githubusercontent.com/1145973/38279264-80e7b706-376d-11e8-985f-de9729924b7c.png)

#### Current behavior:

No valida la factura de NCF

#### Expected behavior:

Que valide la factura.

**Comment by herohat** [comment]
@eneldoserrata  te refieres a "Generar NCF" ? Lo hice, luego borre todo lo demás y solo deje el de "Crédito Fiscal" para ese diario.

Luego cree otro diario "'Factura de Consumos" y configure para que este solo el diario de Facturas de Consumo en el listado.   ¿Es así que va o como es el flujo de configuración?

**Comment by yasmanycastillo** [comment]
@herohat El diario de Facturas de Clientes se encarga de manejar tanto las secuencias de Consumidor Final, Fiscal y demas, no necesitas otro diario. En caso de no necesitar x secuencia solo eliminala de la lista. 

La configuracion es:

Marcar la casilla control de NCF
Click al Boton Generar secuencias.

Eso es todo.

**Comment by gustavovalverde** [comment]
@yasmanycastillo @eneldoserrata:
El tema es que una de las validaciones que hace el código es la de `if len <= 1, para confirmar si ya el diario fue configurado. Sin embargo, para que esto no cause confusión debemos hacer una de dos:
1 - Debería haber un booleano que diga 'Activa', y que estas sean las únicas secuencias que se consuman
2- No debería estar la validación del `len` por si el usuario quierre borrar todas las demás y dejar 1.

**Comment by herohat** [comment]
Gracias @yasmanycastillo por la aclaración.   Me quedan un par de dudas al respecto.

1:   Cuales serían las secuencias correctas a escoger aquí:

![image](https://user-images.githubusercontent.com/1145973/38434711-5a5cfa2e-399d-11e8-9eb2-589ca93b8e14.png)

La secuencia "Secuencia de Crédito Fiscal" parece estar bien pues tiene:

![image](https://user-images.githubusercontent.com/1145973/38434791-a9a0388a-399d-11e8-956f-f89805e84c31.png)
 
Pero la secuencia "Customer Invoices: Refund" en realidad no luce correcta, debería configurarla manualmente correcto?

![image](https://user-images.githubusercontent.com/1145973/38434831-d153b9ba-399d-11e8-95ed-e6778dc5ff15.png)


Gracias.

**Comment by gustavovalverde** [comment]
@herohat, no hay porqué configurar una secuencia de NC (Refund) a parte, ya en esa misma tienes la de NC

**Comment by herohat** [comment]
Gracias @gustavovalverde por la aclaración.
