### ISSUE TITLE
[10.0] AttributeError: 'ir.sequence' object has no attribute '_get_prefix_suffix'

### ISSUE THREAD

**Issue by herohat** [odoo-dominicana/l10n-dominicana#99]
#### Impacted versions:

10.0 Branch

#### Steps to reproduce:

- Crear una factura
- Agregarle dos o más productos con ITBIS
- Seleccionar el diario "Crédito Fiscal" o "Consumidor Final"
- Grabar
- Validar

#### Current behavior:

Devuelve un error:

..
..
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_sequence.py", line 243, in next_by_id
    return self._next()
  File "/etc/odoo/l10n-dominicana/ncf_manager/models/ir_sequence.py", line 45, in _next
    return seq_date.with_context(ir_sequence_date_range=seq_date.date_from)._next()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_sequence.py", line 328, in _next
    return self.sequence_id.get_next_char(number_next)
  File "/etc/odoo/l10n-dominicana/ncf_manager/models/ir_sequence.py", line 23, in get_next_char
    interpolated_prefix, interpolated_suffix = self._get_prefix_suffix()
AttributeError: 'ir.sequence' object has no attribute '_get_prefix_suffix'

#### Expected behavior:

Validar la factura correctamente y generar el NCF.

#### Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/1145973/38435478-b7fb9166-399f-11e8-96ef-d9948e0fff19.png)

![image](https://user-images.githubusercontent.com/1145973/38435491-c390d54a-399f-11e8-8835-d8f256c49160.png)

![image](https://user-images.githubusercontent.com/1145973/38435510-d0f003b4-399f-11e8-9405-db86c735247e.png)

**Comment by gustavovalverde** [comment]
Fixed by ac86b9606f821012e9a92ab38148470adf0b1c79
